import json
import random
import os

OUT_DIR = "/Users/murthy/.gemini/antigravity/scratch/time-tuk-game/src/data/questions/class_7/maths"
os.makedirs(OUT_DIR, exist_ok=True)
random.seed(42)

def shuffle_options(ans_en, ans_kn, wrong_en, wrong_kn):
    comb = list(zip([ans_en] + wrong_en, [ans_kn] + wrong_kn))
    random.shuffle(comb)
    e, k = zip(*comb)
    return list(e), list(k)

def make_single(id_str, diff, q_en, q_kn, ans_en, ans_kn, wrong_en, wrong_kn, res_en, res_kn, img=None):
    e_opt, k_opt = shuffle_options(ans_en, ans_kn, wrong_en, wrong_kn)
    q = {
        "id": id_str, "type": "image_single" if img else "single", "difficulty": diff,
        "en": {"question": q_en, "options": e_opt, "answer": ans_en, "reasoning": res_en},
        "kn": {"question": q_kn, "options": k_opt, "answer": ans_kn, "reasoning": res_kn}
    }
    if img: q["image"] = img
    return q

def make_multi(id_str, diff, q_en, q_kn, ans_en, ans_kn, wrong_en, wrong_kn, res_en, res_kn, img=None):
    comb = list(zip(ans_en + wrong_en, ans_kn + wrong_kn))
    random.shuffle(comb)
    e_opt, k_opt = zip(*comb)
    q = {
        "id": id_str, "type": "image_multiple" if img else "multiple", "difficulty": diff,
        "en": {"question": q_en, "options": list(e_opt), "answer": ans_en, "reasoning": res_en},
        "kn": {"question": q_kn, "options": list(k_opt), "answer": ans_kn, "reasoning": res_kn}
    }
    if img: q["image"] = img
    return q

def make_match(id_str, diff, q_en, q_kn, pairs_en, pairs_kn, res_en, res_kn):
    return {
        "id": id_str, "type": "match", "difficulty": diff,
        "en": {"question": q_en, "pairs": [{"left": l, "right": r} for l, r in pairs_en], "reasoning": res_en},
        "kn": {"question": q_kn, "pairs": [{"left": l, "right": r} for l, r in pairs_kn], "reasoning": res_kn}
    }

def num_line_svg(start, end, points):
    svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 100'>"
    svg += "<line x1='20' y1='50' x2='280' y2='50' stroke='#2563EB' stroke-width='2'/>"
    step = 240 / (end - start)
    for i in range(start, end + 1):
        x = 30 + (i - start) * step
        svg += f"<line x1='{x}' y1='40' x2='{x}' y2='60' stroke='#2563EB' stroke-width='1.5'/>"
        svg += f"<text x='{x}' y='75' fill='#1F2937' font-family='Arial' font-size='12' text-anchor='middle'>{i}</text>"
    for p in points:
        val, col, lbl = p
        px = 30 + (val - start) * step
        svg += f"<circle cx='{px}' cy='50' r='6' fill='{col}'/>"
        if lbl:
            svg += f"<text x='{px}' y='30' fill='{col}' font-family='Arial' font-size='14' text-anchor='middle' font-weight='bold'>{lbl}</text>"
    svg += "</svg>"
    return {"type": "svg", "svg": svg, "alt": {"en": "Number line diagram", "kn": "ಸಂಖ್ಯಾ ರೇಖೆಯ ಚಿತ್ರ"}}

def geom_svg(shape, labels):
    if shape == "triangle":
        svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 200'>"
        svg += "<polygon points='150,30 50,150 250,150' fill='none' stroke='#2563EB' stroke-width='2'/>"
        svg += f"<text x='90' y='80' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle' transform='rotate(-50, 90, 80)'>{labels.get('a','')}</text>"
        svg += f"<text x='210' y='80' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle' transform='rotate(50, 210, 80)'>{labels.get('b','')}</text>"
        svg += f"<text x='150' y='170' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle'>{labels.get('c','')}</text>"
        if labels.get('A'): svg += f"<text x='150' y='20' fill='#1F2937' font-family='Arial' font-size='14' text-anchor='middle'>{labels['A']}</text>"
        if labels.get('B'): svg += f"<text x='35' y='155' fill='#1F2937' font-family='Arial' font-size='14' text-anchor='middle'>{labels['B']}</text>"
        if labels.get('C'): svg += f"<text x='265' y='155' fill='#1F2937' font-family='Arial' font-size='14' text-anchor='middle'>{labels['C']}</text>"
        if labels.get('angleB'): 
            svg += "<path d='M70,150 A20,20 0 0,0 60,135' fill='none' stroke='#EA580C' stroke-width='1.5'/>"
            svg += f"<text x='85' y='145' fill='#EA580C' font-family='Arial' font-size='12'>{labels['angleB']}</text>"
        if labels.get('angleC'):
            svg += "<path d='M230,150 A20,20 0 0,1 240,135' fill='none' stroke='#EA580C' stroke-width='1.5'/>"
            svg += f"<text x='195' y='145' fill='#EA580C' font-family='Arial' font-size='12'>{labels['angleC']}</text>"
        if labels.get('angleA'):
            svg += "<path d='M140,45 A20,20 0 0,0 160,45' fill='none' stroke='#EA580C' stroke-width='1.5'/>"
            svg += f"<text x='150' y='65' fill='#EA580C' font-family='Arial' font-size='12' text-anchor='middle'>{labels['angleA']}</text>"
        svg += "</svg>"
        return {"type": "svg", "svg": svg, "alt": {"en": "Triangle diagram", "kn": "ತ್ರಿಕೋನದ ಚಿತ್ರ"}}
    elif shape == "rect":
        svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 200'>"
        svg += "<rect x='50' y='40' width='200' height='120' fill='none' stroke='#2563EB' stroke-width='2'/>"
        svg += f"<text x='150' y='30' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle'>{labels.get('w','')}</text>"
        svg += f"<text x='270' y='100' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle'>{labels.get('h','')}</text>"
        svg += "</svg>"
        return {"type": "svg", "svg": svg, "alt": {"en": "Rectangle diagram", "kn": "ಆಯತದ ಚಿತ್ರ"}}
    elif shape == "circle":
        svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 300 300'>"
        svg += "<circle cx='150' cy='150' r='100' fill='none' stroke='#2563EB' stroke-width='2'/>"
        svg += "<circle cx='150' cy='150' r='3' fill='#1F2937'/>"
        if labels.get('r'):
            svg += "<line x1='150' y1='150' x2='250' y2='150' stroke='#DC2626' stroke-width='1.5'/>"
            svg += f"<text x='200' y='140' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle'>{labels['r']}</text>"
        if labels.get('d'):
            svg += "<line x1='50' y1='150' x2='250' y2='150' stroke='#DC2626' stroke-width='1.5'/>"
            svg += f"<text x='150' y='140' fill='#DC2626' font-family='Arial' font-size='14' text-anchor='middle'>{labels['d']}</text>"
        svg += "</svg>"
        return {"type": "svg", "svg": svg, "alt": {"en": "Circle diagram", "kn": "ವೃತ್ತದ ಚಿತ್ರ"}}

qs1, qs2, qs3, qs4 = [], [], [], []
i1, i2, i3, i4 = 1, 1, 1, 1

# ================= RATIONAL NUMBERS (30) =================
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 1, "Which rational number is marked by the red dot?", "ಕೆಂಪು ಚುಕ್ಕೆಯಿಂದ ಗುರುತಿಸಲಾದ ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆ ಯಾವುದು?", "3", "3", ["1", "4", "2"], ["1", "4", "2"], "The dot is on the number 3.", "ಚುಕ್ಕೆಯು ಸಂಖ್ಯೆ 3 ರ ಮೇಲಿದೆ.", num_line_svg(0, 5, [(3, "#DC2626", "?")]))); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 1, "Which rational number is marked on this number line?", "ಈ ಸಂಖ್ಯಾ ರೇಖೆಯ ಮೇಲೆ ಗುರುತಿಸಲಾದ ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆ ಯಾವುದು?", "-2", "-2", ["-1", "2", "0"], ["-1", "2", "0"], "The point is at -2.", "ಬಿಂದುವು -2 ನಲ್ಲಿದೆ.", num_line_svg(-5, 5, [(-2, "#DC2626", "?")]))); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 2, "What is the distance between the two marked points?", "ಗುರುತಿಸಲಾದ ಎರಡು ಬಿಂದುಗಳ ನಡುವಿನ ಅಂತರವೆಷ್ಟು?", "4 units", "4 ಮಾನಗಳು", ["3 units", "5 units", "2 units"], ["3 ಮಾನಗಳು", "5 ಮಾನಗಳು", "2 ಮಾನಗಳು"], "Distance from -1 to 3 is 3 - (-1) = 4.", "-1 ರಿಂದ 3 ರವರೆಗಿನ ಅಂತರ 3 - (-1) = 4.", num_line_svg(-3, 5, [(-1, "#059669", "A"), (3, "#059669", "B")]))); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 2, "Which point represents 0?", "ಯಾವ ಬಿಂದುವು 0 ಅನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ?", "The middle tick", "ಮಧ್ಯದ ಗುರುತು", ["Leftmost", "Rightmost", "None"], ["ಎಡಭಾಗದ ತುದಿಯ", "ಬಲಭಾಗದ ತುದಿಯ", "ಯಾವುದೂ ಅಲ್ಲ"], "0 is exactly between -2 and 2.", "-2 ಮತ್ತು 2 ರ ಮಧ್ಯದಲ್ಲಿ 0 ಇರುತ್ತದೆ.", num_line_svg(-2, 2, [(0, "#DC2626", "?")]))); i1+=1
qs1.append(make_multi(f"c7_math_rat_{i1:03d}", 2, "Which of these integers lie between the two dots?", "ಎರಡು ಚುಕ್ಕೆಗಳ ನಡುವೆ ಇರುವ ಪೂರ್ಣಾಂಕಗಳು ಯಾವುವು?", ["1", "2", "3"], ["1", "2", "3"], ["0", "4", "5"], ["0", "4", "5"], "The numbers 1, 2, and 3 lie between 0 and 4.", "0 ಮತ್ತು 4 ರ ನಡುವೆ 1, 2, 3 ಸಂಖ್ಯೆಗಳಿವೆ.", num_line_svg(0, 5, [(0, "#059669", ""), (4, "#059669", "")]))); i1+=1

for n, d, ans, w1, w2, w3 in [("1/5", "2/5", "3/5", "2/10", "4/5", "1/10"), ("3/7", "2/7", "5/7", "6/7", "1/7", "5/14")]:
    qs1.append(make_single(f"c7_math_rat_{i1:03d}", 1, f"What is the sum of {n} and {d}?", f"{n} ಮತ್ತು {d} ರ ಮೊತ್ತವೆಷ್ಟು?", ans, ans, [w1, w2, w3], [w1, w2, w3], "Add the numerators.", "ಅಂಶಗಳನ್ನು ಸೇರಿಸಿ."))
    i1+=1
for frac, ans, w1, w2, w3 in [("4/8", "1/2", "1/4", "2/3", "3/4"), ("15/20", "3/4", "1/2", "2/5", "4/5"), ("10/25", "2/5", "1/5", "3/5", "2/3"), ("9/12", "3/4", "1/4", "1/2", "2/3"), ("6/18", "1/3", "1/2", "2/3", "1/6"), ("12/16", "3/4", "1/4", "1/2", "2/3")]:
    qs1.append(make_single(f"c7_math_rat_{i1:03d}", 1, f"What is {frac} in its simplest form?", f"{frac} ನ ಸರಳ ರೂಪ ಯಾವುದು?", ans, ans, [w1, w2, w3], [w1, w2, w3], "Divide numerator and denominator by their HCF.", "ಅಂಶ ಮತ್ತು ಛೇದವನ್ನು ಅವುಗಳ ಮ.ಸಾ.ಅ ದಿಂದ ಭಾಗಿಸಿ."))
    i1+=1

for expr, ans, w1, w2, w3 in [("1/2 + 1/3", "5/6", "2/5", "1/5", "1/6"), ("3/4 - 1/2", "1/4", "2/2", "1/2", "3/8"), ("2/3 * 3/4", "1/2", "5/7", "6/12", "1/3"), ("3/5 ÷ 2/5", "3/2", "6/25", "1/5", "5/2"), ("1/4 + 2/5", "13/20", "3/9", "3/20", "8/20"), ("7/8 - 1/4", "5/8", "6/4", "6/8", "3/4")]:
    qs1.append(make_single(f"c7_math_rat_{i1:03d}", 2, f"Solve: {expr}", f"ಪರಿಹರಿಸಿ: {expr}", ans, ans, [w1, w2, w3], [w1, w2, w3], "Use LCM for addition/subtraction, and standard rules for multiplication/division.", "ಸಂಕಲನ/ವ್ಯವಕಲನಕ್ಕೆ ಲ.ಸಾ.ಅ ಬಳಸಿ, ಗುಣಾಕಾರ/ಭಾಗಾಕಾರಕ್ಕೆ ಸಾಮಾನ್ಯ ನಿಯಮ ಬಳಸಿ."))
    i1+=1

qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "A rope of length 15/2 meters is cut into 5 equal pieces. What is the length of each piece?", "15/2 ಮೀಟರ್ ಉದ್ದದ ಹಗ್ಗವನ್ನು 5 ಸಮಾನ ತುಂಡುಗಳಾಗಿ ಕತ್ತರಿಸಲಾಗಿದೆ. ಪ್ರತಿ ತುಂಡಿನ ಉದ್ದವೆಷ್ಟು?", "3/2 meters", "3/2 ಮೀಟರ್", ["5/2 meters", "1/2 meters", "15/10 meters"], ["5/2 ಮೀಟರ್", "1/2 ಮೀಟರ್", "15/10 ಮೀಟರ್"], "Divide 15/2 by 5.", "15/2 ಅನ್ನು 5 ರಿಂದ ಭಾಗಿಸಿ.")); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "Find x if 2/3 of x is 16.", "x ನ 2/3 ರಷ್ಟು 16 ಆಗಿದ್ದರೆ, x ಅನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "24", "24", ["32", "12", "48"], ["32", "12", "48"], "(2/3)*x = 16 => x = 16 * 3 / 2 = 24", "(2/3)*x = 16 => x = 16 * 3 / 2 = 24")); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "What should be added to -5/8 to get 3/4?", "-5/8 ಗೆ ಎಷ್ಟನ್ನು ಸೇರಿಸಿದರೆ 3/4 ಸಿಗುತ್ತದೆ?", "11/8", "11/8", ["1/8", "-1/8", "7/8"], ["1/8", "-1/8", "7/8"], "3/4 - (-5/8) = 6/8 + 5/8 = 11/8.", "3/4 - (-5/8) = 6/8 + 5/8 = 11/8.")); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "The product of two rational numbers is -15/28. If one of them is -3/7, what is the other?", "ಎರಡು ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆಗಳ ಗುಣಲಬ್ಧ -15/28. ಅವುಗಳಲ್ಲಿ ಒಂದು -3/7 ಆಗಿದ್ದರೆ, ಮತ್ತೊಂದು ಯಾವುದು?", "5/4", "5/4", ["-5/4", "4/5", "-4/5"], ["-5/4", "4/5", "-4/5"], "(-15/28) ÷ (-3/7) = (-15/28) * (-7/3) = 5/4.", "(-15/28) ÷ (-3/7) = (-15/28) * (-7/3) = 5/4.")); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "Which is greater: -3/4 or -2/3?", "-3/4 ಅಥವಾ -2/3 ಗಳಲ್ಲಿ ಯಾವುದು ದೊಡ್ಡದು?", "-2/3", "-2/3", ["-3/4", "Both are equal", "Cannot be determined"], ["-3/4", "ಎರಡೂ ಸಮ", "ನಿರ್ಧರಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ"], "-2/3 (-0.66) is greater than -3/4 (-0.75).", "-2/3 (-0.66), -3/4 (-0.75) ಗಿಂತ ದೊಡ್ಡದು.")); i1+=1
qs1.append(make_single(f"c7_math_rat_{i1:03d}", 3, "Simplify: (1/2 * 1/3) + (1/4 * 1/2)", "ಸಂಕ್ಷೇಪಿಸಿ: (1/2 * 1/3) + (1/4 * 1/2)", "7/24", "7/24", ["1/6", "1/8", "5/24"], ["1/6", "1/8", "5/24"], "1/6 + 1/8 = 4/24 + 3/24 = 7/24.", "1/6 + 1/8 = 4/24 + 3/24 = 7/24.")); i1+=1

qs1.append(make_multi(f"c7_math_rat_{i1:03d}", 1, "Which of the following are positive rational numbers?", "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುವು ಧನ ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆಗಳು?", ["3/5", "8/9", "1/2"], ["3/5", "8/9", "1/2"], ["-2/3", "-4/7"], ["-2/3", "-4/7"], "Positive rational numbers have the same sign for numerator and denominator.", "ಧನ ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆಗಳಲ್ಲಿ ಅಂಶ ಮತ್ತು ಛೇದ ಎರಡೂ ಒಂದೇ ಚಿಹ್ನೆಯನ್ನು ಹೊಂದಿರುತ್ತವೆ.")); i1+=1
qs1.append(make_multi(f"c7_math_rat_{i1:03d}", 2, "Which of the following fractions are equivalent to 1/2?", "ಕೆಳಗಿನ ಯಾವ ಭಿನ್ನರಾಶಿಗಳು 1/2 ಗೆ ಸಮಾನವಾಗಿವೆ?", ["2/4", "3/6", "5/10"], ["2/4", "3/6", "5/10"], ["3/4", "2/5"], ["3/4", "2/5"], "Multiplying numerator and denominator by the same number gives equivalent fractions.", "ಅಂಶ ಮತ್ತು ಛೇದವನ್ನು ಒಂದೇ ಸಂಖ್ಯೆಯಿಂದ ಗುಣಿಸಿದಾಗ ಸಮಾನ ಭಿನ್ನರಾಶಿಗಳು ಸಿಗುತ್ತವೆ.")); i1+=1
qs1.append(make_multi(f"c7_math_rat_{i1:03d}", 2, "Which of these expressions equal 1?", "ಈ ಕೆಳಗಿನ ಯಾವ ಅಭಿವ್ಯಕ್ತಿಗಳ ಬೆಲೆ 1 ಆಗಿದೆ?", ["1/2 + 1/2", "3/4 + 1/4", "2/3 + 1/3"], ["1/2 + 1/2", "3/4 + 1/4", "2/3 + 1/3"], ["1/2 - 1/2", "1/4 + 1/2"], ["1/2 - 1/2", "1/4 + 1/2"], "Fractions that add up to a whole equal 1.", "ಒಂದು ಪೂರ್ಣವನ್ನು ರೂಪಿಸುವ ಭಿನ್ನರಾಶಿಗಳ ಮೊತ್ತ 1 ಆಗಿರುತ್ತದೆ.")); i1+=1
qs1.append(make_multi(f"c7_math_rat_{i1:03d}", 3, "Identify the rational numbers that lie between 0 and 1.", "0 ಮತ್ತು 1 ರ ನಡುವೆ ಇರುವ ಭಾಗಲಬ್ಧ ಸಂಖ್ಯೆಗಳನ್ನು ಗುರುತಿಸಿ.", ["1/2", "3/4", "7/8"], ["1/2", "3/4", "7/8"], ["3/2", "5/4"], ["3/2", "5/4"], "Proper fractions lie between 0 and 1.", "ಕ್ರಮ ಭಿನ್ನರಾಶಿಗಳು 0 ಮತ್ತು 1 ರ ನಡುವೆ ಇರುತ್ತವೆ.")); i1+=1

qs1.append(make_match(f"c7_math_rat_{i1:03d}", 1, "Match the fraction with its simplest form.", "ಭಿನ್ನರಾಶಿಯನ್ನು ಅದರ ಸರಳ ರೂಪದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("4/8", "1/2"), ("6/9", "2/3"), ("2/10", "1/5"), ("9/12", "3/4")], [("4/8", "1/2"), ("6/9", "2/3"), ("2/10", "1/5"), ("9/12", "3/4")], "Divide numerator and denominator by their highest common factor.", "ಅಂಶ ಮತ್ತು ಛೇದವನ್ನು ಅವುಗಳ ಅತಿದೊಡ್ಡ ಸಾಮಾನ್ಯ ಅಪವರ್ತನದಿಂದ ಭಾಗಿಸಿ.")); i1+=1
qs1.append(make_match(f"c7_math_rat_{i1:03d}", 2, "Match the operation with its result.", "ಕ್ರಿಯೆಯನ್ನು ಅದರ ಫಲಿತಾಂಶದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("1/2 + 1/2", "1"), ("1/2 - 1/2", "0"), ("1/2 * 1/2", "1/4"), ("1/2 ÷ 1/2", "1")], [("1/2 + 1/2", "1"), ("1/2 - 1/2", "0"), ("1/2 * 1/2", "1/4"), ("1/2 ÷ 1/2", "1")], "Basic fraction arithmetic rules apply.", "ಭಿನ್ನರಾಶಿಗಳ ಮೂಲ ಗಣಿತದ ನಿಯಮಗಳು ಅನ್ವಯಿಸುತ್ತವೆ.")); i1+=1
qs1.append(make_match(f"c7_math_rat_{i1:03d}", 2, "Match the fractions to their decimals.", "ಭಿನ್ನರಾಶಿಗಳನ್ನು ಅವುಗಳ ದಶಮಾಂಶಗಳಿಗೆ ಹೊಂದಿಸಿ.", [("1/2", "0.5"), ("1/4", "0.25"), ("3/4", "0.75"), ("1/5", "0.2")], [("1/2", "0.5"), ("1/4", "0.25"), ("3/4", "0.75"), ("1/5", "0.2")], "Divide numerator by denominator.", "ಅಂಶವನ್ನು ಛೇದದಿಂದ ಭಾಗಿಸಿ.")); i1+=1
qs1.append(make_match(f"c7_math_rat_{i1:03d}", 3, "Match the word problem with the correct expression.", "ಪದ ಸಮಸ್ಯೆಯನ್ನು ಸರಿಯಾದ ಅಭಿವ್ಯಕ್ತಿಯೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Half of a quarter", "1/2 * 1/4"), ("Double of one-third", "2 * 1/3"), ("One less than half", "1/2 - 1"), ("Quarter of a half", "1/4 * 1/2")], [("ಕಾಲು ಭಾಗದ ಅರ್ಧ", "1/2 * 1/4"), ("ಮೂರನೇ ಒಂದರ ಎರಡರಷ್ಟು", "2 * 1/3"), ("ಅರ್ಧಕ್ಕಿಂತ ಒಂದು ಕಡಿಮೆ", "1/2 - 1"), ("ಅರ್ಧದ ಕಾಲು ಭಾಗ", "1/4 * 1/2")], "Translate English to mathematical operations.", "ವಾಕ್ಯಗಳನ್ನು ಗಣಿತದ ಕ್ರಿಯೆಗಳಾಗಿ ಭಾಷಾಂತರಿಸಿ.")); i1+=1
qs1.append(make_match(f"c7_math_rat_{i1:03d}", 3, "Match the reciprocal.", "ವ್ಯುತ್ಕ್ರಮವನ್ನು (reciprocal) ಹೊಂದಿಸಿ.", [("2/3", "3/2"), ("-4/5", "-5/4"), ("7", "1/7"), ("-1/2", "-2")], [("2/3", "3/2"), ("-4/5", "-5/4"), ("7", "1/7"), ("-1/2", "-2")], "Reciprocal of a/b is b/a.", "a/b ಯ ವ್ಯುತ್ಕ್ರಮ b/a ಆಗಿದೆ.")); i1+=1

# ================= PRACTICAL GEOMETRY (30) =================
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "What is the length of side AC in this triangle?", "ಈ ತ್ರಿಕೋನದಲ್ಲಿ AC ಬಾಹುವಿನ ಉದ್ದವೆಷ್ಟು?", "5 cm", "5 ಸೆಂ.ಮೀ.", ["3 cm", "4 cm", "6 cm"], ["3 ಸೆಂ.ಮೀ.", "4 ಸೆಂ.ಮೀ.", "6 ಸೆಂ.ಮೀ."], "The diagram shows AC = 5 cm.", "ಚಿತ್ರದಲ್ಲಿ AC = 5 ಸೆಂ.ಮೀ. ಎಂದು ತೋರಿಸಲಾಗಿದೆ.", geom_svg("triangle", {"a": "3 cm", "b": "4 cm", "c": "5 cm", "A": "C", "B": "A", "C": "B"}))); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "What is the measure of angle A in this triangle if the other two are 60° and 50°?", "ಇತರ ಎರಡು ಕೋನಗಳು 60° ಮತ್ತು 50° ಆಗಿದ್ದರೆ, ಈ ತ್ರಿಕೋನದಲ್ಲಿ ಕೋನ A ಯ ಅಳತೆ ಎಷ್ಟು?", "70°", "70°", ["60°", "80°", "90°"], ["60°", "80°", "90°"], "Sum of angles is 180°. 180 - (60+50) = 70.", "ಕೋನಗಳ ಮೊತ್ತ 180°. 180 - (60+50) = 70.", geom_svg("triangle", {"angleB": "60°", "angleC": "50°", "A": "A", "B": "B", "C": "C", "c": "8 cm"}))); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "Which criterion can be used to construct this triangle if only 3 sides are given?", "ಕೇವಲ 3 ಬಾಹುಗಳನ್ನು ನೀಡಿದ್ದರೆ, ಈ ತ್ರಿಕೋನವನ್ನು ರಚಿಸಲು ಯಾವ ನಿಯಮವನ್ನು ಬಳಸಬಹುದು?", "SSS", "SSS (ಬಾಹು-ಬಾಹು-ಬಾಹು)", ["SAS", "ASA", "RHS"], ["SAS", "ASA", "RHS"], "SSS stands for Side-Side-Side.", "SSS ಎಂದರೆ ಬಾಹು-ಬಾಹು-ಬಾಹು.", geom_svg("triangle", {"a": "6 cm", "b": "7 cm", "c": "8 cm"}))); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "If angle B is 90°, what type of triangle is this?", "ಕೋನ B 90° ಆಗಿದ್ದರೆ, ಇದು ಯಾವ ರೀತಿಯ ತ್ರಿಕೋನ?", "Right-angled", "ಲಂಬಕೋನ ತ್ರಿಕೋನ", ["Equilateral", "Acute-angled", "Obtuse-angled"], ["ಸಮಬಾಹು", "ಲಘುಕೋನ", "ವಿಶಾಲಕೋನ"], "A triangle with one 90° angle is a right-angled triangle.", "ಒಂದು 90° ಕೋನವನ್ನು ಹೊಂದಿರುವ ತ್ರಿಕೋನವನ್ನು ಲಂಬಕೋನ ತ್ರಿಕೋನ ಎನ್ನುತ್ತಾರೆ.", geom_svg("triangle", {"angleB": "90°", "B": "B"}))); i2+=1
qs2.append(make_multi(f"c7_math_geom_{i2:03d}", 3, "Which of the following are necessary to construct this unique triangle?", "ಈ ನಿರ್ದಿಷ್ಟ ತ್ರಿಕೋನವನ್ನು ರಚಿಸಲು ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಅಗತ್ಯ?", ["Length of AB", "Length of BC", "Angle B"], ["AB ಯ ಉದ್ದ", "BC ಯ ಉದ್ದ", "ಕೋನ B"], ["Angle A", "Angle C"], ["ಕೋನ A", "ಕೋನ C"], "This requires the SAS (Side-Angle-Side) criterion.", "ಇದಕ್ಕೆ SAS (ಬಾಹು-ಕೋನ-ಬಾಹು) ನಿಯಮದ ಅಗತ್ಯವಿದೆ.", geom_svg("triangle", {"angleB": "45°", "c": "6 cm", "a": "5 cm", "B": "B"}))); i2+=1

qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "What does SSS stand for in triangle construction?", "ತ್ರಿಕೋನ ರಚನೆಯಲ್ಲಿ SSS ಎಂದರೆ ಏನು?", "Side-Side-Side", "ಬಾಹು-ಬಾಹು-ಬಾಹು (Side-Side-Side)", ["Angle-Side-Angle", "Side-Angle-Side", "Right-Hypotenuse-Side"], ["ಕೋನ-ಬಾಹು-ಕೋನ", "ಬಾಹು-ಕೋನ-ಬಾಹು", "ಲಂಬಕೋನ-ವಿಕರ್ಣ-ಬಾಹು"], "SSS means all three sides are given.", "SSS ಎಂದರೆ ಮೂರೂ ಬಾಹುಗಳನ್ನು ನೀಡಲಾಗಿದೆ ಎಂದರ್ಥ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "What tool is used to draw an arc of a specific radius?", "ನಿರ್ದಿಷ್ಟ ತ್ರಿಜ್ಯದ ಕಂಸವನ್ನು ಎಳೆಯಲು ಯಾವ ಉಪಕರಣವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ?", "Compass", "ಕೈವಾರ (Compass)", ["Protractor", "Ruler", "Divider"], ["ಕೋನಮಾಪಕ", "ಅಳತೆಪಟ್ಟಿ", "ವಿಭಾಜಕ"], "A compass is used to draw arcs and circles.", "ಕಂಸಗಳು ಮತ್ತು ವೃತ್ತಗಳನ್ನು ಎಳೆಯಲು ಕೈವಾರವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "What does SAS stand for?", "SAS ಎಂದರೆ ಏನು?", "Side-Angle-Side", "ಬಾಹು-ಕೋನ-ಬಾಹು (Side-Angle-Side)", ["Side-Side-Side", "Angle-Side-Angle", "Right-Angle-Side"], ["ಬಾಹು-ಬಾಹು-ಬಾಹು", "ಕೋನ-ಬಾಹು-ಕೋನ", "ಲಂಬಕೋನ-ಬಾಹು"], "SAS stands for Side-Angle-Side.", "SAS ಎಂದರೆ ಬಾಹು-ಕೋನ-ಬಾಹು.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "Which tool is used to measure angles?", "ಕೋನಗಳನ್ನು ಅಳೆಯಲು ಯಾವ ಉಪಕರಣವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ?", "Protractor", "ಕೋನಮಾಪಕ (Protractor)", ["Compass", "Ruler", "Set Square"], ["ಕೈವಾರ", "ಅಳತೆಪಟ್ಟಿ", "ಮೂಲೆಮಟ್ಟ"], "A protractor measures angles in degrees.", "ಕೋನಮಾಪಕವು ಕೋನಗಳನ್ನು ಡಿಗ್ರಿಗಳಲ್ಲಿ ಅಳೆಯುತ್ತದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "The sum of the angles in a triangle is always:", "ತ್ರಿಕೋನದಲ್ಲಿರುವ ಕೋನಗಳ ಮೊತ್ತ ಯಾವಾಗಲೂ:", "180°", "180°", ["90°", "360°", "270°"], ["90°", "360°", "270°"], "A triangle's interior angles sum to 180 degrees.", "ತ್ರಿಕೋನದ ಒಳಕೋನಗಳ ಮೊತ್ತ 180 ಡಿಗ್ರಿ ಆಗಿರುತ್ತದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "What does RHS stand for?", "RHS ಎಂದರೆ ಏನು?", "Right angle-Hypotenuse-Side", "ಲಂಬಕೋನ-ವಿಕರ್ಣ-ಬಾಹು (Right angle-Hypotenuse-Side)", ["Right-Half-Side", "Real-Hypotenuse-Side", "Right-Height-Side"], ["ಬಲ-ಅರ್ಧ-ಬಾಹು", "ನೈಜ-ವಿಕರ್ಣ-ಬಾಹು", "ಲಂಬ-ಎತ್ತರ-ಬಾಹು"], "RHS is a criterion for right-angled triangles.", "RHS ಲಂಬಕೋನ ತ್ರಿಕೋನಗಳ ರಚನೆಯ ನಿಯಮವಾಗಿದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "Can a triangle be constructed with angles 60°, 60°, and 70°?", "60°, 60° ಮತ್ತು 70° ಕೋನಗಳನ್ನು ಬಳಸಿ ತ್ರಿಕೋನವನ್ನು ರಚಿಸಬಹುದೇ?", "No", "ಇಲ್ಲ", ["Yes", "Only if sides are given", "Sometimes"], ["ಹೌದು", "ಬಾಹುಗಳನ್ನು ಕೊಟ್ಟರೆ ಮಾತ್ರ", "ಕೆಲವೊಮ್ಮೆ"], "The sum is 190°, which is not 180°.", "ಮೊತ್ತವು 190° ಆಗುತ್ತದೆ, 180° ಅಲ್ಲ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 1, "Can you construct a triangle with sides 2 cm, 3 cm, and 6 cm?", "2 ಸೆಂ.ಮೀ, 3 ಸೆಂ.ಮೀ ಮತ್ತು 6 ಸೆಂ.ಮೀ ಬಾಹುಗಳಿರುವ ತ್ರಿಕೋನವನ್ನು ರಚಿಸಬಹುದೇ?", "No", "ಇಲ್ಲ", ["Yes", "Only if it is right-angled", "Only if it is isosceles"], ["ಹೌದು", "ಅದು ಲಂಬಕೋನವಾಗಿದ್ದರೆ ಮಾತ್ರ", "ಅದು ಸಮದ್ವಿಬಾಹುವಾಗಿದ್ದರೆ ಮಾತ್ರ"], "Sum of two sides (2+3) must be greater than the third side (6). 5 is not greater than 6.", "ಎರಡು ಬಾಹುಗಳ ಮೊತ್ತ (2+3) ಮೂರನೇ ಬಾಹುವಿಗಿಂತ (6) ದೊಡ್ಡದಾಗಿರಬೇಕು. 5, 6ಕ್ಕಿಂತ ದೊಡ್ಡದಲ್ಲ.")); i2+=1

qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "To construct an equilateral triangle of side 5 cm, which criterion is used?", "5 ಸೆಂ.ಮೀ ಬಾಹುವುಳ್ಳ ಸಮಬಾಹು ತ್ರಿಕೋನವನ್ನು ರಚಿಸಲು ಯಾವ ನಿಯಮವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ?", "SSS", "SSS", ["SAS", "ASA", "RHS"], ["SAS", "ASA", "RHS"], "All three sides are 5 cm.", "ಮೂರೂ ಬಾಹುಗಳು 5 ಸೆಂ.ಮೀ ಆಗಿರುತ್ತವೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "In a right-angled triangle, if the hypotenuse is 10 cm and one side is 6 cm, which criterion is used to construct it?", "ಒಂದು ಲಂಬಕೋನ ತ್ರಿಕೋನದಲ್ಲಿ, ವಿಕರ್ಣ 10 ಸೆಂ.ಮೀ ಮತ್ತು ಒಂದು ಬಾಹು 6 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದನ್ನು ರಚಿಸಲು ಯಾವ ನಿಯಮ ಬಳಸಲಾಗುತ್ತದೆ?", "RHS", "RHS", ["SSS", "SAS", "ASA"], ["SSS", "SAS", "ASA"], "Right angle, Hypotenuse, and one Side are given.", "ಲಂಬಕೋನ, ವಿಕರ್ಣ ಮತ್ತು ಒಂದು ಬಾಹುವನ್ನು ನೀಡಲಾಗಿದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "If two angles of a triangle are 40° and 50°, what is the third angle?", "ತ್ರಿಕೋನದ ಎರಡು ಕೋನಗಳು 40° ಮತ್ತು 50° ಆಗಿದ್ದರೆ, ಮೂರನೇ ಕೋನ ಎಷ್ಟು?", "90°", "90°", ["100°", "80°", "60°"], ["100°", "80°", "60°"], "180 - (40 + 50) = 90°.", "180 - (40 + 50) = 90°.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "Which criterion involves knowing two angles and the included side?", "ಎರಡು ಕೋನಗಳು ಮತ್ತು ಅವುಗಳ ನಡುವಿನ ಬಾಹುವನ್ನು ತಿಳಿದುಕೊಳ್ಳುವುದನ್ನು ಒಳಗೊಂಡಿರುವ ನಿಯಮ ಯಾವುದು?", "ASA", "ASA (ಕೋನ-ಬಾಹು-ಕೋನ)", ["SAS", "SSS", "RHS"], ["SAS", "SSS", "RHS"], "ASA stands for Angle-Side-Angle.", "ASA ಎಂದರೆ ಕೋನ-ಬಾಹು-ಕೋನ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "To draw a line parallel to a given line through a point outside it, we use the property of:", "ಒಂದು ರೇಖೆಯ ಹೊರಗಿನ ಬಿಂದುವಿನ ಮೂಲಕ ಆ ರೇಖೆಗೆ ಸಮಾಂತರ ರೇಖೆಯನ್ನು ಎಳೆಯಲು, ನಾವು ಯಾವ ಗುಣವನ್ನು ಬಳಸುತ್ತೇವೆ?", "Alternate interior angles", "ಪರ್ಯಾಯ ಒಳಕೋನಗಳು", ["Right angles", "Adjacent angles", "Straight angles"], ["ಲಂಬಕೋನಗಳು", "ಪಾರ್ಶ್ವ ಕೋನಗಳು", "ಸರಳ ಕೋನಗಳು"], "Equal alternate interior angles ensure lines are parallel.", "ಸಮಾನ ಪರ್ಯಾಯ ಒಳಕೋನಗಳು ರೇಖೆಗಳು ಸಮಾಂತರವಾಗಿರುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತವೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 2, "If you are given AB = 5 cm, ∠A = 60° and ∠B = 70°, which criterion will you use?", "AB = 5 ಸೆಂ.ಮೀ, ∠A = 60° ಮತ್ತು ∠B = 70° ನೀಡಿದ್ದರೆ, ನೀವು ಯಾವ ನಿಯಮವನ್ನು ಬಳಸುತ್ತೀರಿ?", "ASA", "ASA", ["SAS", "SSS", "RHS"], ["SAS", "SSS", "RHS"], "Two angles and the included side are given.", "ಎರಡು ಕೋನಗಳು ಮತ್ತು ಒಳಗೊಂಡಿರುವ ಬಾಹುವನ್ನು ನೀಡಲಾಗಿದೆ.")); i2+=1

qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "In triangle ABC, AB = 5 cm, BC = 5 cm, and ∠B = 60°. What type of triangle is it?", "ತ್ರಿಕೋನ ABC ಯಲ್ಲಿ, AB = 5 ಸೆಂ.ಮೀ, BC = 5 ಸೆಂ.ಮೀ, ಮತ್ತು ∠B = 60°. ಇದು ಯಾವ ರೀತಿಯ ತ್ರಿಕೋನ?", "Equilateral", "ಸಮಬಾಹು ತ್ರಿಕೋನ", ["Isosceles but not equilateral", "Scalene", "Right-angled"], ["ಸಮದ್ವಿಬಾಹು ಆದರೆ ಸಮಬಾಹು ಅಲ್ಲ", "ಅಸಮಬಾಹು", "ಲಂಬಕೋನ ತ್ರಿಕೋನ"], "An isosceles triangle with a 60° angle between equal sides is equilateral.", "ಸಮಾನ ಬಾಹುಗಳ ನಡುವೆ 60° ಕೋನವನ್ನು ಹೊಂದಿರುವ ಸಮದ್ವಿಬಾಹು ತ್ರಿಕೋನವು ಸಮಬಾಹು ತ್ರಿಕೋನವಾಗಿರುತ್ತದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "Can we construct a unique triangle if only its three angles are given (e.g. 60°, 60°, 60°)?", "ಕೇವಲ ಅದರ ಮೂರು ಕೋನಗಳನ್ನು ನೀಡಿದ್ದರೆ (ಉದಾ. 60°, 60°, 60°) ನಾವು ಒಂದು ನಿರ್ದಿಷ್ಟ ತ್ರಿಕೋನವನ್ನು ರಚಿಸಬಹುದೇ?", "No, we can draw infinitely many of different sizes.", "ಇಲ್ಲ, ನಾವು ಬೇರೆ ಬೇರೆ ಗಾತ್ರದ ಅನಂತ ತ್ರಿಕೋನಗಳನ್ನು ರಚಿಸಬಹುದು.", ["Yes, exactly one unique triangle.", "No, such a triangle does not exist.", "Yes, if they are acute angles."], ["ಹೌದು, ನಿಖರವಾಗಿ ಒಂದೇ ತ್ರಿಕೋನ.", "ಇಲ್ಲ, ಅಂತಹ ತ್ರಿಕೋನ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.", "ಹೌದು, ಅವು ಲಘುಕೋನಗಳಾಗಿದ್ದರೆ."], "AAA is not a congruence criterion; it only guarantees similar triangles.", "AAA ಸರ್ವಸಮತೆಯ ನಿಯಮವಲ್ಲ; ಅದು ಕೇವಲ ಸಮರೂಪ ತ್ರಿಕೋನಗಳನ್ನು ನೀಡುತ್ತದೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "To construct triangle LMN with LM = 4 cm, ∠M = 100° and ∠N = 50°, we first need to find ∠L. What is it?", "LM = 4 ಸೆಂ.ಮೀ, ∠M = 100° ಮತ್ತು ∠N = 50° ಇರುವ LMN ತ್ರಿಕೋನವನ್ನು ರಚಿಸಲು, ನಾವು ಮೊದಲು ∠L ಅನ್ನು ಕಂಡುಹಿಡಿಯಬೇಕು. ಅದು ಎಷ್ಟು?", "30°", "30°", ["40°", "50°", "20°"], ["40°", "50°", "20°"], "180 - (100 + 50) = 30°.", "180 - (100 + 50) = 30°.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "In a right angled triangle PQR (right angled at Q), PR = 13 cm, QR = 5 cm. What is the length of PQ?", "ಲಂಬಕೋನ ತ್ರಿಕೋನ PQR ನಲ್ಲಿ (Q ನಲ್ಲಿ ಲಂಬಕೋನ), PR = 13 ಸೆಂ.ಮೀ, QR = 5 ಸೆಂ.ಮೀ. ಹಾಗಾದರೆ PQ ಉದ್ದ ಎಷ್ಟು?", "12 cm", "12 ಸೆಂ.ಮೀ.", ["8 cm", "144 cm", "10 cm"], ["8 ಸೆಂ.ಮೀ.", "144 ಸೆಂ.ಮೀ.", "10 ಸೆಂ.ಮೀ."], "Using Pythagoras theorem: PQ² = 13² - 5² = 169 - 25 = 144. PQ = 12.", "ಪೈಥಾಗರಸ್ ಪ್ರಮೇಯದ ಪ್ರಕಾರ: PQ² = 13² - 5² = 169 - 25 = 144. PQ = 12.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "Can you construct triangle XYZ if XY = 5 cm, YZ = 3 cm, and ZX = 8 cm?", "XY = 5 ಸೆಂ.ಮೀ, YZ = 3 ಸೆಂ.ಮೀ, ಮತ್ತು ZX = 8 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ತ್ರಿಕೋನ XYZ ಅನ್ನು ರಚಿಸಲು ಸಾಧ್ಯವೇ?", "No, because sum of two sides equals the third.", "ಇಲ್ಲ, ಏಕೆಂದರೆ ಎರಡು ಬಾಹುಗಳ ಮೊತ್ತ ಮೂರನೇ ಬಾಹುವಿಗೆ ಸಮವಾಗಿದೆ.", ["Yes, by SSS criterion.", "No, because 8 cm is too long.", "Yes, it is a right-angled triangle."], ["ಹೌದು, SSS ನಿಯಮದ ಮೂಲಕ.", "ಇಲ್ಲ, ಏಕೆಂದರೆ 8 ಸೆಂ.ಮೀ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ.", "ಹೌದು, ಇದು ಒಂದು ಲಂಬಕೋನ ತ್ರಿಕೋನ."], "5 + 3 = 8. The points will be collinear.", "5 + 3 = 8. ಬಿಂದುಗಳು ಏಕರೇಖಾಗತವಾಗಿರುತ್ತವೆ.")); i2+=1
qs2.append(make_single(f"c7_math_geom_{i2:03d}", 3, "While constructing a line parallel to a given line using compass and ruler, which geometric concept is primarily used?", "ಕೈವಾರ ಮತ್ತು ಅಳತೆಪಟ್ಟಿಯನ್ನು ಬಳಸಿ ದತ್ತ ರೇಖೆಗೆ ಸಮಾಂತರ ರೇಖೆಯನ್ನು ರಚಿಸುವಾಗ, ಯಾವ ರೇಖಾಗಣಿತದ ಪರಿಕಲ್ಪನೆಯನ್ನು ಮುಖ್ಯವಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ?", "Copying an angle", "ಕೋನವನ್ನು ನಕಲಿಸುವುದು", ["Drawing a perpendicular bisector", "Finding the midpoint", "Trisecting an angle"], ["ಲಂಬ ವಿಭಾಜಕವನ್ನು ಎಳೆಯುವುದು", "ಮಧ್ಯಬಿಂದುವನ್ನು ಕಂಡುಹಿಡಿಯುವುದು", "ಕೋನವನ್ನು ತ್ರೈಭಾಜಿಸುವುದು"], "We copy an alternate interior angle to draw the parallel line.", "ಸಮಾಂತರ ರೇಖೆಯನ್ನು ಎಳೆಯಲು ನಾವು ಪರ್ಯಾಯ ಒಳಕೋನವನ್ನು ನಕಲಿಸುತ್ತೇವೆ.")); i2+=1

qs2.append(make_multi(f"c7_math_geom_{i2:03d}", 2, "Which sets of side lengths can form a triangle?", "ಯಾವ ಬಾಹುಗಳ ಉದ್ದಗಳ ಸೆಟ್‌ಗಳು ತ್ರಿಕೋನವನ್ನು ರೂಪಿಸಬಹುದು?", ["3, 4, 5", "5, 5, 5"], ["3, 4, 5", "5, 5, 5"], ["1, 2, 3", "2, 3, 6"], ["1, 2, 3", "2, 3, 6"], "The sum of any two sides must be strictly greater than the third side.", "ಯಾವುದೇ ಎರಡು ಬಾಹುಗಳ ಮೊತ್ತವು ಮೂರನೇ ಬಾಹುವಿಗಿಂತ ಕಡ್ಡಾಯವಾಗಿ ದೊಡ್ಡದಾಗಿರಬೇಕು.")); i2+=1
qs2.append(make_multi(f"c7_math_geom_{i2:03d}", 2, "Which sets of angles can form a triangle?", "ಯಾವ ಕೋನಗಳ ಸೆಟ್‌ಗಳು ತ್ರಿಕೋನವನ್ನು ರೂಪಿಸಬಹುದು?", ["60°, 60°, 60°", "90°, 45°, 45°"], ["60°, 60°, 60°", "90°, 45°, 45°"], ["90°, 90°, 10°", "50°, 50°, 50°"], ["90°, 90°, 10°", "50°, 50°, 50°"], "The sum of the three angles must be exactly 180°.", "ಮೂರು ಕೋನಗಳ ಮೊತ್ತವು ನಿಖರವಾಗಿ 180° ಆಗಿರಬೇಕು.")); i2+=1
qs2.append(make_multi(f"c7_math_geom_{i2:03d}", 2, "Which elements are required for the SAS criterion?", "SAS ನಿಯಮಕ್ಕೆ ಯಾವ ಅಂಶಗಳು ಬೇಕಾಗುತ್ತವೆ?", ["Two sides", "The included angle"], ["ಎರಡು ಬಾಹುಗಳು", "ಅವುಗಳ ನಡುವಿನ ಕೋನ"], ["Three sides", "A right angle"], ["ಮೂರು ಬಾಹುಗಳು", "ಒಂದು ಲಂಬಕೋನ"], "SAS means Side-Angle-Side (the angle must be between the two given sides).", "SAS ಎಂದರೆ ಬಾಹು-ಕೋನ-ಬಾಹು (ಕೋನವು ನೀಡಲಾದ ಎರಡು ಬಾಹುಗಳ ನಡುವೆ ಇರಬೇಕು).")); i2+=1
qs2.append(make_multi(f"c7_math_geom_{i2:03d}", 2, "Which of these are triangle congruence criteria?", "ಇವುಗಳಲ್ಲಿ ಯಾವುವು ತ್ರಿಕೋನ ಸರ್ವಸಮತೆಯ ನಿಯಮಗಳಾಗಿವೆ?", ["SSS", "SAS", "ASA", "RHS"], ["SSS", "SAS", "ASA", "RHS"], ["AAA", "SSA"], ["AAA", "SSA"], "AAA and SSA do not guarantee unique congruent triangles.", "AAA ಮತ್ತು SSA ಗಳು ನಿರ್ದಿಷ್ಟ ಸರ್ವಸಮ ತ್ರಿಕೋನಗಳನ್ನು ಖಾತರಿಪಡಿಸುವುದಿಲ್ಲ.")); i2+=1

qs2.append(make_match(f"c7_math_geom_{i2:03d}", 1, "Match the tool with its primary use in geometry.", "ಉಪಕರಣವನ್ನು ರೇಖಾಗಣಿತದಲ್ಲಿ ಅದರ ಪ್ರಾಥಮಿಕ ಉಪಯೋಗದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Compass", "Drawing arcs and circles"), ("Protractor", "Measuring angles"), ("Ruler", "Drawing straight lines"), ("Divider", "Comparing lengths")], [("ಕೈವಾರ (Compass)", "ಕಂಸಗಳು ಮತ್ತು ವೃತ್ತಗಳನ್ನು ಎಳೆಯುವುದು"), ("ಕೋನಮಾಪಕ (Protractor)", "ಕೋನಗಳನ್ನು ಅಳೆಯುವುದು"), ("ಅಳತೆಪಟ್ಟಿ (Ruler)", "ಸರಳ ರೇಖೆಗಳನ್ನು ಎಳೆಯುವುದು"), ("ವಿಭಾಜಕ (Divider)", "ಉದ್ದಗಳನ್ನು ಹೋಲಿಸುವುದು")], "Each tool has a specific purpose in construction.", "ಪ್ರತಿಯೊಂದು ಉಪಕರಣವು ರಚನೆಯಲ್ಲಿ ನಿರ್ದಿಷ್ಟ ಉದ್ದೇಶವನ್ನು ಹೊಂದಿದೆ.")); i2+=1
qs2.append(make_match(f"c7_math_geom_{i2:03d}", 2, "Match the construction criterion to its meaning.", "ರಚನೆಯ ನಿಯಮವನ್ನು ಅದರ ಅರ್ಥದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("SSS", "Three sides given"), ("SAS", "Two sides and included angle"), ("ASA", "Two angles and included side"), ("RHS", "Right angle, hypotenuse, side")], [("SSS", "ಮೂರು ಬಾಹುಗಳನ್ನು ನೀಡಲಾಗಿದೆ"), ("SAS", "ಎರಡು ಬಾಹುಗಳು ಮತ್ತು ನಡುವಿನ ಕೋನ"), ("ASA", "ಎರಡು ಕೋನಗಳು ಮತ್ತು ನಡುವಿನ ಬಾಹು"), ("RHS", "ಲಂಬಕೋನ, ವಿಕರ್ಣ, ಬಾಹು")], "These are the standard criteria for triangle construction.", "ಇವು ತ್ರಿಕೋನ ರಚನೆಯ ಪ್ರಮಾಣಿತ ನಿಯಮಗಳಾಗಿವೆ.")); i2+=1
qs2.append(make_match(f"c7_math_geom_{i2:03d}", 2, "Match the triangle type to its property.", "ತ್ರಿಕೋನದ ಪ್ರಕಾರವನ್ನು ಅದರ ಗುಣಲಕ್ಷಣದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Equilateral", "All sides equal"), ("Isosceles", "Two sides equal"), ("Scalene", "No sides equal"), ("Right-angled", "One angle is 90 degrees")], [("ಸಮಬಾಹು", "ಎಲ್ಲಾ ಬಾಹುಗಳು ಸಮ"), ("ಸಮದ್ವಿಬಾಹು", "ಎರಡು ಬಾಹುಗಳು ಸಮ"), ("ಅಸಮಬಾಹು", "ಯಾವುದೇ ಬಾಹುಗಳು ಸಮನಾಗಿರುವುದಿಲ್ಲ"), ("ಲಂಬಕೋನ", "ಒಂದು ಕೋನ 90 ಡಿಗ್ರಿ")], "Triangles are classified by their sides and angles.", "ತ್ರಿಕೋನಗಳನ್ನು ಅವುಗಳ ಬಾಹುಗಳು ಮತ್ತು ಕೋನಗಳಿಂದ ವರ್ಗೀಕರಿಸಲಾಗುತ್ತದೆ.")); i2+=1
qs2.append(make_match(f"c7_math_geom_{i2:03d}", 3, "Match the given parts to the required criterion to construct it.", "ತ್ರಿಕೋನವನ್ನು ರಚಿಸಲು ನೀಡಲಾದ ಭಾಗಗಳನ್ನು ಅಗತ್ಯವಿರುವ ನಿಯಮದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("AB=5, BC=6, AC=7", "SSS"), ("AB=5, ∠B=60°, BC=6", "SAS"), ("∠A=40°, AB=5, ∠B=50°", "ASA"), ("∠B=90°, AC=10, AB=6", "RHS")], [("AB=5, BC=6, AC=7", "SSS"), ("AB=5, ∠B=60°, BC=6", "SAS"), ("∠A=40°, AB=5, ∠B=50°", "ASA"), ("∠B=90°, AC=10, AB=6", "RHS")], "Identify which components (Side or Angle) are given.", "ಯಾವ ಘಟಕಗಳನ್ನು (ಬಾಹು ಅಥವಾ ಕೋನ) ನೀಡಲಾಗಿದೆ ಎಂಬುದನ್ನು ಗುರುತಿಸಿ.")); i2+=1
qs2.append(make_match(f"c7_math_geom_{i2:03d}", 3, "Match the third angle for a triangle given the first two.", "ಮೊದಲ ಎರಡು ಕೋನಗಳನ್ನು ನೀಡಿದಾಗ ತ್ರಿಕೋನದ ಮೂರನೇ ಕೋನವನ್ನು ಹೊಂದಿಸಿ.", [("50° and 60°", "70°"), ("90° and 45°", "45°"), ("110° and 30°", "40°"), ("60° and 60°", "60°")], [("50° ಮತ್ತು 60°", "70°"), ("90° ಮತ್ತು 45°", "45°"), ("110° ಮತ್ತು 30°", "40°"), ("60° ಮತ್ತು 60°", "60°")], "The sum of all three angles is always 180°.", "ಮೂರು ಕೋನಗಳ ಮೊತ್ತ ಯಾವಾಗಲೂ 180° ಆಗಿರುತ್ತದೆ.")); i2+=1

# ================= PERIMETER AND AREA (30) =================
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "What is the area of this rectangle?", "ಈ ಆಯತದ ವಿಸ್ತೀರ್ಣ ಎಷ್ಟು?", "12 cm²", "12 ಚ.ಸೆಂ.ಮೀ.", ["14 cm²", "7 cm²", "24 cm²"], ["14 ಚ.ಸೆಂ.ಮೀ.", "7 ಚ.ಸೆಂ.ಮೀ.", "24 ಚ.ಸೆಂ.ಮೀ."], "Area = length × width = 4 × 3 = 12.", "ವಿಸ್ತೀರ್ಣ = ಉದ್ದ × ಅಗಲ = 4 × 3 = 12.", geom_svg("rect", {"w": "4 cm", "h": "3 cm"}))); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "What is the perimeter of this rectangle?", "ಈ ಆಯತದ ಸುತ್ತಳತೆ ಎಷ್ಟು?", "14 cm", "14 ಸೆಂ.ಮೀ.", ["12 cm", "7 cm", "24 cm"], ["12 ಸೆಂ.ಮೀ.", "7 ಸೆಂ.ಮೀ.", "24 ಸೆಂ.ಮೀ."], "Perimeter = 2(length + width) = 2(4 + 3) = 14.", "ಸುತ್ತಳತೆ = 2(ಉದ್ದ + ಅಗಲ) = 2(4 + 3) = 14.", geom_svg("rect", {"w": "4 cm", "h": "3 cm"}))); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "If the radius of this circle is 7 cm, what is its circumference? (Use π = 22/7)", "ಈ ವೃತ್ತದ ತ್ರಿಜ್ಯ 7 ಸೆಂ.ಮೀ. ಆಗಿದ್ದರೆ, ಅದರ ಸುತ್ತಳತೆ ಎಷ್ಟು? (π = 22/7 ಬಳಸಿ)", "44 cm", "44 ಸೆಂ.ಮೀ.", ["22 cm", "154 cm", "14 cm"], ["22 ಸೆಂ.ಮೀ.", "154 ಸೆಂ.ಮೀ.", "14 ಸೆಂ.ಮೀ."], "C = 2πr = 2 * (22/7) * 7 = 44.", "C = 2πr = 2 * (22/7) * 7 = 44.", geom_svg("circle", {"r": "7 cm"}))); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "What is the area of this circle if its radius is 7 cm? (Use π = 22/7)", "ಈ ವೃತ್ತದ ತ್ರಿಜ್ಯ 7 ಸೆಂ.ಮೀ. ಆಗಿದ್ದರೆ, ಅದರ ವಿಸ್ತೀರ್ಣ ಎಷ್ಟು? (π = 22/7 ಬಳಸಿ)", "154 cm²", "154 ಚ.ಸೆಂ.ಮೀ.", ["44 cm²", "22 cm²", "49 cm²"], ["44 ಚ.ಸೆಂ.ಮೀ.", "22 ಚ.ಸೆಂ.ಮೀ.", "49 ಚ.ಸೆಂ.ಮೀ."], "Area = πr² = (22/7) * 7 * 7 = 154.", "ವಿಸ್ತೀರ್ಣ = πr² = (22/7) * 7 * 7 = 154.", geom_svg("circle", {"r": "7 cm"}))); i3+=1
qs3.append(make_multi(f"c7_math_perim_{i3:03d}", 3, "If a triangle has a base of 6 cm and height of 4 cm, which of these are true?", "ಒಂದು ತ್ರಿಕೋನದ ಪಾದ 6 ಸೆಂ.ಮೀ. ಮತ್ತು ಎತ್ತರ 4 ಸೆಂ.ಮೀ. ಆಗಿದ್ದರೆ, ಇವುಗಳಲ್ಲಿ ಯಾವುದು ಸರಿ?", ["Area is 12 cm²", "Area is (1/2)×6×4 cm²"], ["ವಿಸ್ತೀರ್ಣ 12 ಚ.ಸೆಂ.ಮೀ.", "ವಿಸ್ತೀರ್ಣ (1/2)×6×4 ಚ.ಸೆಂ.ಮೀ."], ["Area is 24 cm²", "Perimeter is 10 cm"], ["ವಿಸ್ತೀರ್ಣ 24 ಚ.ಸೆಂ.ಮೀ.", "ಸುತ್ತಳತೆ 10 ಸೆಂ.ಮೀ."], "Area of triangle = 1/2 × base × height.", "ತ್ರಿಕೋನದ ವಿಸ್ತೀರ್ಣ = 1/2 × ಪಾದ × ಎತ್ತರ.", geom_svg("triangle", {"c": "6 cm (Base)", "a": "Height=4"}))); i3+=1

qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "The area of a square is 25 cm². What is its side length?", "ಒಂದು ಚೌಕದ ವಿಸ್ತೀರ್ಣ 25 ಚ.ಸೆಂ.ಮೀ. ಅದರ ಬಾಹುವಿನ ಉದ್ದವೆಷ್ಟು?", "5 cm", "5 ಸೆಂ.ಮೀ.", ["10 cm", "6.25 cm", "12.5 cm"], ["10 ಸೆಂ.ಮೀ.", "6.25 ಸೆಂ.ಮೀ.", "12.5 ಸೆಂ.ಮೀ."], "Area = side × side. 5 × 5 = 25.", "ವಿಸ್ತೀರ್ಣ = ಬಾಹು × ಬಾಹು. 5 × 5 = 25.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "What is the formula for the perimeter of a rectangle?", "ಆಯತದ ಸುತ್ತಳತೆಯ ಸೂತ್ರವೇನು?", "2(l + b)", "2(l + b)", ["l × b", "4 × l", "l + b"], ["l × b", "4 × l", "l + b"], "Perimeter of rectangle = 2(length + breadth).", "ಆಯತದ ಸುತ್ತಳತೆ = 2(ಉದ್ದ + ಅಗಲ).")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "The distance around a circular region is known as its:", "ವೃತ್ತಾಕಾರದ ಪ್ರದೇಶದ ಸುತ್ತಲಿನ ಅಂತರವನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ?", "Circumference", "ಪರಿಧಿ (Circumference)", ["Area", "Diameter", "Radius"], ["ವಿಸ್ತೀರ್ಣ", "ವ್ಯಾಸ", "ತ್ರಿಜ್ಯ"], "The boundary of a circle is its circumference.", "ವೃತ್ತದ ಗಡಿಯನ್ನು ಅದರ ಪರಿಧಿ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "If the diameter of a circle is 10 cm, what is its radius?", "ವೃತ್ತದ ವ್ಯಾಸ 10 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದರ ತ್ರಿಜ್ಯ ಎಷ್ಟು?", "5 cm", "5 ಸೆಂ.ಮೀ.", ["20 cm", "10 cm", "31.4 cm"], ["20 ಸೆಂ.ಮೀ.", "10 ಸೆಂ.ಮೀ.", "31.4 ಸೆಂ.ಮೀ."], "Radius = Diameter / 2.", "ತ್ರಿಜ್ಯ = ವ್ಯಾಸ / 2.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "What is the area of a triangle with base 10 cm and height 5 cm?", "10 ಸೆಂ.ಮೀ ಪಾದ ಮತ್ತು 5 ಸೆಂ.ಮೀ ಎತ್ತರವುಳ್ಳ ತ್ರಿಕೋನದ ವಿಸ್ತೀರ್ಣ ಎಷ್ಟು?", "25 cm²", "25 ಚ.ಸೆಂ.ಮೀ.", ["50 cm²", "15 cm²", "30 cm²"], ["50 ಚ.ಸೆಂ.ಮೀ.", "15 ಚ.ಸೆಂ.ಮೀ.", "30 ಚ.ಸೆಂ.ಮೀ."], "Area = 1/2 × base × height = 1/2 × 10 × 5 = 25.", "ವಿಸ್ತೀರ್ಣ = 1/2 × ಪಾದ × ಎತ್ತರ = 1/2 × 10 × 5 = 25.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "Find the perimeter of a square with side 8 m.", "8 ಮೀ. ಬಾಹುವಿರುವ ಚೌಕದ ಸುತ್ತಳತೆಯನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "32 m", "32 ಮೀ.", ["64 m", "16 m", "24 m"], ["64 ಮೀ.", "16 ಮೀ.", "24 ಮೀ."], "Perimeter = 4 × side = 4 × 8 = 32.", "ಸುತ್ತಳತೆ = 4 × ಬಾಹು = 4 × 8 = 32.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "Which unit is used to measure area?", "ವಿಸ್ತೀರ್ಣವನ್ನು ಅಳೆಯಲು ಯಾವ ಮಾನವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ?", "Square meters (m²)", "ಚದರ ಮೀಟರ್ (m²)", ["Meters (m)", "Cubic meters (m³)", "Liters (L)"], ["ಮೀಟರ್ (m)", "ಘನ ಮೀಟರ್ (m³)", "ಲೀಟರ್ (L)"], "Area is measured in square units.", "ವಿಸ್ತೀರ್ಣವನ್ನು ಚದರ ಮಾನಗಳಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 1, "Value of π (pi) is approximately:", "π (ಪೈ) ನ ಅಂದಾಜು ಬೆಲೆ:", "22/7 or 3.14", "22/7 ಅಥವಾ 3.14", ["7/22 or 0.314", "3.41", "2.14"], ["7/22 ಅಥವಾ 0.314", "3.41", "2.14"], "Pi is approximately 22/7 or 3.14.", "ಪೈ ಬೆಲೆ ಸುಮಾರು 22/7 ಅಥವಾ 3.14 ಆಗಿದೆ.")); i3+=1

qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "A rectangular garden is 30m long and 20m wide. What is the length of wire needed to fence it?", "ಒಂದು ಆಯತಾಕಾರದ ಉದ್ಯಾನವನ 30 ಮೀ ಉದ್ದ ಮತ್ತು 20 ಮೀ ಅಗಲವಿದೆ. ಅದಕ್ಕೆ ಬೇಲಿ ಹಾಕಲು ಬೇಕಾಗುವ ತಂತಿಯ ಉದ್ದ ಎಷ್ಟು?", "100 m", "100 ಮೀ.", ["600 m", "50 m", "120 m"], ["600 ಮೀ.", "50 ಮೀ.", "120 ಮೀ."], "Perimeter = 2(30 + 20) = 100.", "ಸುತ್ತಳತೆ = 2(30 + 20) = 100.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "If the circumference of a circle is 31.4 cm, find its radius. (Use π = 3.14)", "ವೃತ್ತದ ಪರಿಧಿ 31.4 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದರ ತ್ರಿಜ್ಯವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ. (π = 3.14 ಬಳಸಿ)", "5 cm", "5 ಸೆಂ.ಮೀ.", ["10 cm", "3.14 cm", "15.7 cm"], ["10 ಸೆಂ.ಮೀ.", "3.14 ಸೆಂ.ಮೀ.", "15.7 ಸೆಂ.ಮೀ."], "2 * 3.14 * r = 31.4 => 6.28r = 31.4 => r = 5.", "2 * 3.14 * r = 31.4 => 6.28r = 31.4 => r = 5.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "Find the area of a parallelogram with base 8 cm and height 4 cm.", "8 ಸೆಂ.ಮೀ ಪಾದ ಮತ್ತು 4 ಸೆಂ.ಮೀ ಎತ್ತರವಿರುವ ಸಮಾಂತರ ಚತುರ್ಭುಜದ ವಿಸ್ತೀರ್ಣವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "32 cm²", "32 ಚ.ಸೆಂ.ಮೀ.", ["16 cm²", "24 cm²", "12 cm²"], ["16 ಚ.ಸೆಂ.ಮೀ.", "24 ಚ.ಸೆಂ.ಮೀ.", "12 ಚ.ಸೆಂ.ಮೀ."], "Area of parallelogram = base × height = 8 × 4 = 32.", "ಸಮಾಂತರ ಚತುರ್ಭುಜದ ವಿಸ್ತೀರ್ಣ = ಪಾದ × ಎತ್ತರ = 8 × 4 = 32.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "The area of a rectangular sheet is 500 cm². If the length is 25 cm, what is its width?", "ಒಂದು ಆಯತಾಕಾರದ ಹಾಳೆಯ ವಿಸ್ತೀರ್ಣ 500 ಚ.ಸೆಂ.ಮೀ. ಉದ್ದ 25 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದರ ಅಗಲ ಎಷ್ಟು?", "20 cm", "20 ಸೆಂ.ಮೀ.", ["25 cm", "10 cm", "50 cm"], ["25 ಸೆಂ.ಮೀ.", "10 ಸೆಂ.ಮೀ.", "50 ಸೆಂ.ಮೀ."], "Width = Area / Length = 500 / 25 = 20.", "ಅಗಲ = ವಿಸ್ತೀರ್ಣ / ಉದ್ದ = 500 / 25 = 20.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "What is the circumference of a circle of diameter 14 cm? (π = 22/7)", "14 ಸೆಂ.ಮೀ ವ್ಯಾಸವಿರುವ ವೃತ್ತದ ಪರಿಧಿ ಎಷ್ಟು? (π = 22/7)", "44 cm", "44 ಸೆಂ.ಮೀ.", ["22 cm", "88 cm", "154 cm"], ["22 ಸೆಂ.ಮೀ.", "88 ಸೆಂ.ಮೀ.", "154 ಸೆಂ.ಮೀ."], "C = π × d = (22/7) × 14 = 44.", "C = π × d = (22/7) × 14 = 44.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 2, "1 hectare is equal to how many square meters?", "1 ಹೆಕ್ಟೇರ್ ಎಷ್ಟು ಚದರ ಮೀಟರ್‌ಗಳಿಗೆ ಸಮ?", "10,000 m²", "10,000 ಚ.ಮೀ.", ["1,000 m²", "100 m²", "100,000 m²"], ["1,000 ಚ.ಮೀ.", "100 ಚ.ಮೀ.", "100,000 ಚ.ಮೀ."], "1 hectare = 100m × 100m = 10,000 m².", "1 ಹೆಕ್ಟೇರ್ = 100ಮೀ × 100ಮೀ = 10,000 ಚ.ಮೀ.")); i3+=1

qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "A square park has an area of 400 m². A path of width 2m is built inside its boundary. What is the side length of the inner square?", "ಒಂದು ಚೌಕಾಕಾರದ ಉದ್ಯಾನವನದ ವಿಸ್ತೀರ್ಣ 400 ಚ.ಮೀ. ಅದರ ಗಡಿಯೊಳಗೆ 2 ಮೀ. ಅಗಲದ ಹಾದಿಯನ್ನು ನಿರ್ಮಿಸಲಾಗಿದೆ. ಒಳಗಿನ ಚೌಕದ ಬಾಹುವಿನ ಉದ್ದವೆಷ್ಟು?", "16 m", "16 ಮೀ.", ["18 m", "20 m", "14 m"], ["18 ಮೀ.", "20 ಮೀ.", "14 ಮೀ."], "Outer side = 20m. Inner side = 20 - 2(2) = 16m.", "ಹೊರಗಿನ ಬಾಹು = 20ಮೀ. ಒಳಗಿನ ಬಾಹು = 20 - 2(2) = 16ಮೀ.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "The radius of a circular pipe is 10 cm. What length of tape is required to wrap once around the pipe? (π = 3.14)", "ವೃತ್ತಾಕಾರದ ಪೈಪ್‌ನ ತ್ರಿಜ್ಯ 10 ಸೆಂ.ಮೀ. ಪೈಪ್‌ನ ಸುತ್ತಲೂ ಒಮ್ಮೆ ಸುತ್ತಲು ಎಷ್ಟು ಉದ್ದದ ಟೇಪ್ ಬೇಕಾಗುತ್ತದೆ? (π = 3.14)", "62.8 cm", "62.8 ಸೆಂ.ಮೀ.", ["31.4 cm", "314 cm", "6.28 cm"], ["31.4 ಸೆಂ.ಮೀ.", "314 ಸೆಂ.ಮೀ.", "6.28 ಸೆಂ.ಮೀ."], "Length = Circumference = 2 × 3.14 × 10 = 62.8.", "ಉದ್ದ = ಪರಿಧಿ = 2 × 3.14 × 10 = 62.8.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "A wire is in the shape of a square of side 10 cm. If the wire is rebent into a rectangle of length 12 cm, find its breadth.", "ಒಂದು ತಂತಿಯು 10 ಸೆಂ.ಮೀ. ಬಾಹುವಿನ ಚೌಕದ ಆಕಾರದಲ್ಲಿದೆ. ಆ ತಂತಿಯನ್ನು 12 ಸೆಂ.ಮೀ. ಉದ್ದದ ಆಯತವಾಗಿ ಬಾಗಿಸಿದರೆ, ಅದರ ಅಗಲವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "8 cm", "8 ಸೆಂ.ಮೀ.", ["6 cm", "10 cm", "12 cm"], ["6 ಸೆಂ.ಮೀ.", "10 ಸೆಂ.ಮೀ.", "12 ಸೆಂ.ಮೀ."], "Perimeter is same: 40 = 2(12 + b) => 20 = 12 + b => b = 8.", "ಸುತ್ತಳತೆ ಒಂದೇ: 40 = 2(12 + b) => 20 = 12 + b => b = 8.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "Find the area of a circle whose circumference is 31.4 cm (use π = 3.14).", "ವೃತ್ತದ ಪರಿಧಿ 31.4 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದರ ವಿಸ್ತೀರ್ಣವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ (π = 3.14 ಬಳಸಿ).", "78.5 cm²", "78.5 ಚ.ಸೆಂ.ಮೀ.", ["31.4 cm²", "100 cm²", "15.7 cm²"], ["31.4 ಚ.ಸೆಂ.ಮೀ.", "100 ಚ.ಸೆಂ.ಮೀ.", "15.7 ಚ.ಸೆಂ.ಮೀ."], "r = 31.4 / (2*3.14) = 5. Area = 3.14 * 5 * 5 = 78.5.", "r = 31.4 / (2*3.14) = 5. ವಿಸ್ತೀರ್ಣ = 3.14 * 5 * 5 = 78.5.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "A rectangular park is 45m long and 30m wide. A path 2.5m wide is constructed outside the park. Find the area of the path.", "ಒಂದು ಆಯತಾಕಾರದ ಉದ್ಯಾನವನ 45ಮೀ ಉದ್ದ ಮತ್ತು 30ಮೀ ಅಗಲವಿದೆ. ಉದ್ಯಾನವನದ ಹೊರಗೆ 2.5ಮೀ ಅಗಲದ ಹಾದಿಯನ್ನು ನಿರ್ಮಿಸಲಾಗಿದೆ. ಹಾದಿಯ ವಿಸ್ತೀರ್ಣವನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "400 m²", "400 ಚ.ಮೀ.", ["375 m²", "425 m²", "450 m²"], ["375 ಚ.ಮೀ.", "425 ಚ.ಮೀ.", "450 ಚ.ಮೀ."], "Outer = (45+5)×(30+5) = 50×35=1750. Inner = 45×30=1350. Path = 1750-1350 = 400.", "ಹೊರಗಿನದು = 50×35=1750. ಒಳಗಿನದು = 45×30=1350. ಹಾದಿ = 1750-1350 = 400.")); i3+=1
qs3.append(make_single(f"c7_math_perim_{i3:03d}", 3, "If the radius of a circle is doubled, what happens to its area?", "ಒಂದು ವೃತ್ತದ ತ್ರಿಜ್ಯವನ್ನು ದ್ವಿಗುಣಗೊಳಿಸಿದರೆ, ಅದರ ವಿಸ್ತೀರ್ಣ ಏನಾಗುತ್ತದೆ?", "It becomes 4 times", "ಅದು 4 ಪಟ್ಟು ಹೆಚ್ಚಾಗುತ್ತದೆ", ["It doubles", "It halves", "It becomes 8 times"], ["ಅದು ದ್ವಿಗುಣಗೊಳ್ಳುತ್ತದೆ", "ಅದು ಅರ್ಧವಾಗುತ್ತದೆ", "ಅದು 8 ಪಟ್ಟು ಹೆಚ್ಚಾಗುತ್ತದೆ"], "Area = π(2r)² = 4πr², which is 4 times.", "ವಿಸ್ತೀರ್ಣ = π(2r)² = 4πr², ಇದು 4 ಪಟ್ಟು ಹೆಚ್ಚು.")); i3+=1

qs3.append(make_multi(f"c7_math_perim_{i3:03d}", 2, "Which formulas are correct for area?", "ವಿಸ್ತೀರ್ಣಕ್ಕೆ ಯಾವ ಸೂತ್ರಗಳು ಸರಿಯಾಗಿವೆ?", ["Rectangle: l × b", "Triangle: 1/2 × b × h", "Square: side × side"], ["ಆಯತ: l × b", "ತ್ರಿಕೋನ: 1/2 × b × h", "ಚೌಕ: ಬಾಹು × ಬಾಹು"], ["Circle: 2πr", "Parallelogram: 1/2 × b × h"], ["ವೃತ್ತ: 2πr", "ಸಮಾಂತರ ಚತುರ್ಭುಜ: 1/2 × b × h"], "Circle area is πr², parallelogram is b×h.", "ವೃತ್ತದ ವಿಸ್ತೀರ್ಣ πr², ಸಮಾಂತರ ಚತುರ್ಭುಜದ ವಿಸ್ತೀರ್ಣ b×h.")); i3+=1
qs3.append(make_multi(f"c7_math_perim_{i3:03d}", 2, "Which formulas are correct for perimeter or circumference?", "ಸುತ್ತಳತೆ ಅಥವಾ ಪರಿಧಿಗೆ ಯಾವ ಸೂತ್ರಗಳು ಸರಿಯಾಗಿವೆ?", ["Circle: 2πr", "Rectangle: 2(l+b)", "Square: 4 × side"], ["ವೃತ್ತ: 2πr", "ಆಯತ: 2(l+b)", "ಚೌಕ: 4 × ಬಾಹು"], ["Circle: πr²", "Triangle: l×b×h"], ["ವೃತ್ತ: πr²", "ತ್ರಿಕೋನ: l×b×h"], "Perimeter measures boundary lengths.", "ಸುತ್ತಳತೆಯು ಗಡಿಯ ಉದ್ದವನ್ನು ಅಳೆಯುತ್ತದೆ.")); i3+=1
qs3.append(make_multi(f"c7_math_perim_{i3:03d}", 2, "Which shapes have their area measured in square units?", "ಯಾವ ಆಕಾರಗಳ ವಿಸ್ತೀರ್ಣವನ್ನು ಚದರ ಮಾನಗಳಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ?", ["Circle", "Triangle", "Rectangle"], ["ವೃತ್ತ", "ತ್ರಿಕೋನ", "ಆಯತ"], ["Line", "Angle"], ["ರೇಖೆ", "ಕೋನ"], "All 2D shapes have area in square units.", "ಎಲ್ಲಾ ದ್ವಿ-ಆಯಾಮದ ಆಕಾರಗಳ ವಿಸ್ತೀರ್ಣವನ್ನು ಚದರ ಮಾನಗಳಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ.")); i3+=1
qs3.append(make_multi(f"c7_math_perim_{i3:03d}", 3, "If a rectangle has perimeter 20 cm, which of these could be its dimensions (l, b)?", "ಒಂದು ಆಯತದ ಸುತ್ತಳತೆ 20 ಸೆಂ.ಮೀ ಆಗಿದ್ದರೆ, ಅದರ ಉದ್ದ ಮತ್ತು ಅಗಲಗಳು (l, b) ಇವುಗಳಲ್ಲಿ ಯಾವುದಾಗಿರಬಹುದು?", ["l=6, b=4", "l=7, b=3", "l=8, b=2"], ["l=6, b=4", "l=7, b=3", "l=8, b=2"], ["l=10, b=10", "l=5, b=4"], ["l=10, b=10", "l=5, b=4"], "2(l+b) = 20 => l+b = 10.", "2(l+b) = 20 => l+b = 10.")); i3+=1

qs3.append(make_match(f"c7_math_perim_{i3:03d}", 1, "Match the shape with its perimeter formula.", "ಆಕಾರವನ್ನು ಅದರ ಸುತ್ತಳತೆಯ ಸೂತ್ರದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Rectangle", "2(l + b)"), ("Square", "4 × side"), ("Circle", "2πr"), ("Equilateral Triangle", "3 × side")], [("ಆಯತ", "2(l + b)"), ("ಚೌಕ", "4 × ಬಾಹು"), ("ವೃತ್ತ", "2πr"), ("ಸಮಬಾಹು ತ್ರಿಕೋನ", "3 × ಬಾಹು")], "Formulas for boundary lengths.", "ಗಡಿಯ ಉದ್ದಗಳ ಸೂತ್ರಗಳು.")); i3+=1
qs3.append(make_match(f"c7_math_perim_{i3:03d}", 2, "Match the shape with its area formula.", "ಆಕಾರವನ್ನು ಅದರ ವಿಸ್ತೀರ್ಣದ ಸೂತ್ರದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Rectangle", "l × b"), ("Triangle", "1/2 × b × h"), ("Circle", "πr²"), ("Parallelogram", "b × h")], [("ಆಯತ", "l × b"), ("ತ್ರಿಕೋನ", "1/2 × b × h"), ("ವೃತ್ತ", "πr²"), ("ಸಮಾಂತರ ಚತುರ್ಭುಜ", "b × h")], "Formulas for enclosed space.", "ವಿಸ್ತೀರ್ಣದ ಸೂತ್ರಗಳು.")); i3+=1
qs3.append(make_match(f"c7_math_perim_{i3:03d}", 2, "Match the radius to its circle's circumference (use π=22/7).", "ತ್ರಿಜ್ಯವನ್ನು ವೃತ್ತದ ಪರಿಧಿಗೆ ಹೊಂದಿಸಿ (π=22/7).", [("7 cm", "44 cm"), ("14 cm", "88 cm"), ("3.5 cm", "22 cm"), ("21 cm", "132 cm")], [("7 ಸೆಂ.ಮೀ.", "44 ಸೆಂ.ಮೀ."), ("14 ಸೆಂ.ಮೀ.", "88 ಸೆಂ.ಮೀ."), ("3.5 ಸೆಂ.ಮೀ.", "22 ಸೆಂ.ಮೀ."), ("21 ಸೆಂ.ಮೀ.", "132 ಸೆಂ.ಮೀ.")], "C = 2 * 22/7 * r", "C = 2 * 22/7 * r")); i3+=1
qs3.append(make_match(f"c7_math_perim_{i3:03d}", 3, "Match the side of a square to its area.", "ಚೌಕದ ಬಾಹುವನ್ನು ಅದರ ವಿಸ್ತೀರ್ಣದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("5 cm", "25 cm²"), ("12 cm", "144 cm²"), ("15 cm", "225 cm²"), ("20 cm", "400 cm²")], [("5 ಸೆಂ.ಮೀ.", "25 ಚ.ಸೆಂ.ಮೀ."), ("12 ಸೆಂ.ಮೀ.", "144 ಚ.ಸೆಂ.ಮೀ."), ("15 ಸೆಂ.ಮೀ.", "225 ಚ.ಸೆಂ.ಮೀ."), ("20 ಸೆಂ.ಮೀ.", "400 ಚ.ಸೆಂ.ಮೀ.")], "Area = side × side", "ವಿಸ್ತೀರ್ಣ = ಬಾಹು × ಬಾಹು")); i3+=1
qs3.append(make_match(f"c7_math_perim_{i3:03d}", 3, "Match the dimension with the resulting area for a rectangle.", "ಆಯತದ ಅಳತೆಯನ್ನು ಅದರ ವಿಸ್ತೀರ್ಣದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("l=10, b=5", "50"), ("l=8, b=6", "48"), ("l=12, b=4", "48 "), ("l=15, b=2", "30")], [("l=10, b=5", "50"), ("l=8, b=6", "48"), ("l=12, b=4", "48 "), ("l=15, b=2", "30")], "Area = length × breadth", "ವಿಸ್ತೀರ್ಣ = ಉದ್ದ × ಅಗಲ")); i3+=1

# ================= ALGEBRAIC EXPRESSIONS (30) =================
# Images Single (5)
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "If the length of a rectangle is 'x' and width is 'y', what is its area?", "ಆಯತದ ಉದ್ದ 'x' ಮತ್ತು ಅಗಲ 'y' ಆಗಿದ್ದರೆ, ಅದರ ವಿಸ್ತೀರ್ಣ ಎಷ್ಟು?", "xy", "xy", ["x+y", "2xy", "2(x+y)"], ["x+y", "2xy", "2(x+y)"], "Area is length multiplied by width.", "ವಿಸ್ತೀರ್ಣವು ಉದ್ದ ಮತ್ತು ಅಗಲದ ಗುಣಲಬ್ಧವಾಗಿದೆ.", geom_svg("rect", {"w": "x", "h": "y"}))); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "If the sides of a triangle are a, b, and c, what is its perimeter?", "ತ್ರಿಕೋನದ ಬಾಹುಗಳು a, b ಮತ್ತು c ಆಗಿದ್ದರೆ, ಅದರ ಸುತ್ತಳತೆ ಎಷ್ಟು?", "a + b + c", "a + b + c", ["abc", "2(a+b+c)", "(a+b)/c"], ["abc", "2(a+b+c)", "(a+b)/c"], "Perimeter is the sum of all sides.", "ಸುತ್ತಳತೆಯು ಎಲ್ಲಾ ಬಾಹುಗಳ ಮೊತ್ತವಾಗಿದೆ.", geom_svg("triangle", {"a": "a", "b": "b", "c": "c"}))); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "The number line shows a jump of 'x' and then '3'. What is the total distance from 0?", "ಸಂಖ್ಯಾ ರೇಖೆಯು ಮೊದಲು 'x' ಮತ್ತು ನಂತರ '3' ರ ಜಿಗಿತವನ್ನು ತೋರಿಸುತ್ತದೆ. 0 ದಿಂದ ಒಟ್ಟು ಅಂತರ ಎಷ್ಟು?", "x + 3", "x + 3", ["3x", "x - 3", "3 - x"], ["3x", "x - 3", "3 - x"], "Distance is added: x + 3.", "ಅಂತರವನ್ನು ಸೇರಿಸಲಾಗುತ್ತದೆ: x + 3.", num_line_svg(0, 5, [(2, "#059669", "x"), (5, "#DC2626", "+3")]))); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "If the radius of a circle is 'r', its area is:", "ವೃತ್ತದ ತ್ರಿಜ್ಯ 'r' ಆಗಿದ್ದರೆ, ಅದರ ವಿಸ್ತೀರ್ಣ:", "πr²", "πr²", ["2πr", "πr", "2πr²"], ["2πr", "πr", "2πr²"], "Area of a circle is pi times radius squared.", "ವೃತ್ತದ ವಿಸ್ತೀರ್ಣವು ಪೈ ಮತ್ತು ತ್ರಿಜ್ಯದ ವರ್ಗದ ಗುಣಲಬ್ಧವಾಗಿದೆ.", geom_svg("circle", {"r": "r"}))); i4+=1
qs4.append(make_multi(f"c7_math_alg_{i4:03d}", 3, "For a rectangle with sides '2x' and 'y', which expressions are correct?", "ಬಾಹುಗಳು '2x' ಮತ್ತು 'y' ಆಗಿರುವ ಆಯತಕ್ಕೆ ಯಾವ ಅಭಿವ್ಯಕ್ತಿಗಳು ಸರಿಯಾಗಿವೆ?", ["Area = 2xy", "Perimeter = 4x + 2y"], ["ವಿಸ್ತೀರ್ಣ = 2xy", "ಸುತ್ತಳತೆ = 4x + 2y"], ["Area = x²y", "Perimeter = 2xy"], ["ವಿಸ್ತೀರ್ಣ = x²y", "ಸುತ್ತಳತೆ = 2xy"], "Area = 2x*y. Perimeter = 2(2x+y) = 4x+2y.", "ವಿಸ್ತೀರ್ಣ = 2x*y. ಸುತ್ತಳತೆ = 2(2x+y) = 4x+2y.", geom_svg("rect", {"w": "2x", "h": "y"}))); i4+=1

qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "What is the numerical coefficient of the term -5xy?", "-5xy ಪದದ ಸಂಖ್ಯಾ ಸಹಗುಣಕ ಯಾವುದು?", "-5", "-5", ["5", "xy", "-xy"], ["5", "xy", "-xy"], "The number multiplying the variables is the numerical coefficient.", "ಚರಾಕ್ಷರಗಳನ್ನು ಗುಣಿಸುವ ಸಂಖ್ಯೆಯನ್ನು ಸಂಖ್ಯಾ ಸಹಗುಣಕ ಎನ್ನುತ್ತಾರೆ.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "Which of the following is a binomial?", "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ದ್ವಿಪದೋಕ್ತಿ?", "x + y", "x + y", ["2x", "x²", "xyz"], ["2x", "x²", "xyz"], "A binomial has exactly two terms.", "ದ್ವಿಪದೋಕ್ತಿಯು ನಿಖರವಾಗಿ ಎರಡು ಪದಗಳನ್ನು ಹೊಂದಿರುತ್ತದೆ.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "What are the like terms in the expression 3x + 4y - 2x + 7?", "3x + 4y - 2x + 7 ಅಭಿವ್ಯಕ್ತಿಯಲ್ಲಿರುವ ಸಜಾತೀಯ ಪದಗಳು ಯಾವುವು?", "3x and -2x", "3x ಮತ್ತು -2x", ["3x and 4y", "4y and 7", "-2x and 7"], ["3x ಮತ್ತು 4y", "4y ಮತ್ತು 7", "-2x ಮತ್ತು 7"], "Terms with the same variables are like terms.", "ಒಂದೇ ಚರಾಕ್ಷರಗಳನ್ನು ಹೊಂದಿರುವ ಪದಗಳು ಸಜಾತೀಯ ಪದಗಳು.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "Add 5x and 3x.", "5x ಮತ್ತು 3x ಅನ್ನು ಸೇರಿಸಿ.", "8x", "8x", ["2x", "15x", "8x²"], ["2x", "15x", "8x²"], "5x + 3x = (5+3)x = 8x.", "5x + 3x = (5+3)x = 8x.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "Subtract 2y from 7y.", "7y ನಿಂದ 2y ಅನ್ನು ಕಳೆಯಿರಿ.", "5y", "5y", ["9y", "14y", "5"], ["9y", "14y", "5"], "7y - 2y = (7-2)y = 5y.", "7y - 2y = (7-2)y = 5y.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "What is the value of x + 5 if x = 3?", "x = 3 ಆಗಿದ್ದರೆ, x + 5 ರ ಬೆಲೆ ಎಷ್ಟು?", "8", "8", ["2", "15", "-2"], ["2", "15", "-2"], "3 + 5 = 8.", "3 + 5 = 8.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "The expression '5 subtracted from y' is written as:", "'y ನಿಂದ 5 ನ್ನು ಕಳೆಯುವುದು' ಎಂಬ ಅಭಿವ್ಯಕ್ತಿಯನ್ನು ಹೇಗೆ ಬರೆಯಲಾಗುತ್ತದೆ?", "y - 5", "y - 5", ["5 - y", "5y", "y/5"], ["5 - y", "5y", "y/5"], "Start with y, subtract 5.", "y ನಿಂದ ಪ್ರಾರಂಭಿಸಿ, 5 ನ್ನು ಕಳೆಯಿರಿ.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 1, "The expression for 'x multiplied by 4' is:", "'x ಅನ್ನು 4 ರಿಂದ ಗುಣಿಸಿದಾಗ' ಸಿಗುವ ಅಭಿವ್ಯಕ್ತಿ ಯಾವುದು?", "4x", "4x", ["x+4", "x/4", "4/x"], ["x+4", "x/4", "4/x"], "x * 4 is written as 4x.", "x * 4 ಅನ್ನು 4x ಎಂದು ಬರೆಯಲಾಗುತ್ತದೆ.")); i4+=1

qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "Simplify: (3a + 5b) + (2a - 3b)", "ಸಂಕ್ಷೇಪಿಸಿ: (3a + 5b) + (2a - 3b)", "5a + 2b", "5a + 2b", ["5a + 8b", "a + 2b", "a + 8b"], ["5a + 8b", "a + 2b", "a + 8b"], "Combine like terms: (3a+2a) + (5b-3b) = 5a + 2b.", "ಸಜಾತೀಯ ಪದಗಳನ್ನು ಸೇರಿಸಿ: (3a+2a) + (5b-3b) = 5a + 2b.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "Subtract (x² - y²) from (2x² + 3y²)", "(2x² + 3y²) ನಿಂದ (x² - y²) ಅನ್ನು ಕಳೆಯಿರಿ", "x² + 4y²", "x² + 4y²", ["x² + 2y²", "3x² + 2y²", "3x² + 4y²"], ["x² + 2y²", "3x² + 2y²", "3x² + 4y²"], "(2x² + 3y²) - (x² - y²) = 2x² - x² + 3y² + y² = x² + 4y².", "(2x² + 3y²) - (x² - y²) = 2x² - x² + 3y² + y² = x² + 4y².")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "Find the value of 3x² - 5x + 2 when x = 2.", "x = 2 ಆದಾಗ 3x² - 5x + 2 ರ ಬೆಲೆಯನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "4", "4", ["14", "0", "-4"], ["14", "0", "-4"], "3(2)² - 5(2) + 2 = 12 - 10 + 2 = 4.", "3(2)² - 5(2) + 2 = 12 - 10 + 2 = 4.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "Which of the following is a trinomial?", "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ತ್ರಿಪದೋಕ್ತಿ?", "x + y + z", "x + y + z", ["xy", "x + y", "3xyz"], ["xy", "x + y", "3xyz"], "A trinomial has three terms.", "ತ್ರಿಪದೋಕ್ತಿಯು ಮೂರು ಪದಗಳನ್ನು ಹೊಂದಿರುತ್ತದೆ.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "What should be added to x² + xy + y² to obtain 2x² + 3xy?", "2x² + 3xy ಅನ್ನು ಪಡೆಯಲು x² + xy + y² ಗೆ ಏನನ್ನು ಸೇರಿಸಬೇಕು?", "x² + 2xy - y²", "x² + 2xy - y²", ["x² + 2xy + y²", "-x² - 2xy + y²", "3x² + 4xy + y²"], ["x² + 2xy + y²", "-x² - 2xy + y²", "3x² + 4xy + y²"], "(2x² + 3xy) - (x² + xy + y²) = x² + 2xy - y².", "(2x² + 3xy) - (x² + xy + y²) = x² + 2xy - y².")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 2, "If a = 1 and b = -2, find the value of a² + b² + ab.", "a = 1 ಮತ್ತು b = -2 ಆಗಿದ್ದರೆ, a² + b² + ab ರ ಬೆಲೆಯನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "3", "3", ["5", "1", "7"], ["5", "1", "7"], "1² + (-2)² + (1)(-2) = 1 + 4 - 2 = 3.", "1² + (-2)² + (1)(-2) = 1 + 4 - 2 = 3.")); i4+=1

qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "Simplify: (a + b - c) - (b - a + c)", "ಸಂಕ್ಷೇಪಿಸಿ: (a + b - c) - (b - a + c)", "2a - 2c", "2a - 2c", ["2a + 2b - 2c", "0", "2b - 2c"], ["2a + 2b - 2c", "0", "2b - 2c"], "a + b - c - b + a - c = 2a - 2c.", "a + b - c - b + a - c = 2a - 2c.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "What should be subtracted from 2a + 8b + 10 to get -3a + 7b + 16?", "-3a + 7b + 16 ಅನ್ನು ಪಡೆಯಲು 2a + 8b + 10 ನಿಂದ ಏನನ್ನು ಕಳೆಯಬೇಕು?", "5a + b - 6", "5a + b - 6", ["-a + 15b + 26", "5a - b + 6", "a - b + 6"], ["-a + 15b + 26", "5a - b + 6", "a - b + 6"], "(2a + 8b + 10) - (-3a + 7b + 16) = 5a + b - 6.", "(2a + 8b + 10) - (-3a + 7b + 16) = 5a + b - 6.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "Find the value of the expression n³ - 5n² + 5n - 2 when n = -2.", "n = -2 ಆದಾಗ n³ - 5n² + 5n - 2 ಅಭಿವ್ಯಕ್ತಿಯ ಬೆಲೆಯನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.", "-40", "-40", ["-20", "-16", "-24"], ["-20", "-16", "-24"], "(-2)³ - 5(-2)² + 5(-2) - 2 = -8 - 20 - 10 - 2 = -40.", "(-2)³ - 5(-2)² + 5(-2) - 2 = -8 - 20 - 10 - 2 = -40.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "Identify the coefficient of x in the expression: y²x - y.", "y²x - y ಅಭಿವ್ಯಕ್ತಿಯಲ್ಲಿ x ನ ಸಹಗುಣಕವನ್ನು ಗುರುತಿಸಿ.", "y²", "y²", ["y", "-y", "1"], ["y", "-y", "1"], "The term containing x is y²x. Its coefficient is y².", "x ಅನ್ನು ಒಳಗೊಂಡಿರುವ ಪದ y²x. ಅದರ ಸಹಗುಣಕ y².")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "Simplify: 2x - [3y - {2x - (y - x)}]", "ಸಂಕ್ಷೇಪಿಸಿ: 2x - [3y - {2x - (y - x)}]", "5x - 4y", "5x - 4y", ["-x - 4y", "x + 2y", "5x + 4y"], ["-x - 4y", "x + 2y", "5x + 4y"], "Inner bracket: y-x. Next: 2x-y+x=3x-y. Next: 3y-3x+y=4y-3x. Finally: 2x-(4y-3x)=5x-4y.", "ಒಳಗಿನ ಆವರಣ: y-x. ನಂತರ: 2x-y+x=3x-y. ನಂತರ: 3y-3x+y=4y-3x. ಕೊನೆಯದಾಗಿ: 2x-(4y-3x)=5x-4y.")); i4+=1
qs4.append(make_single(f"c7_math_alg_{i4:03d}", 3, "From the sum of 3x - y + 11 and -y - 11, subtract 3x - y - 11.", "3x - y + 11 ಮತ್ತು -y - 11 ರ ಮೊತ್ತದಿಂದ 3x - y - 11 ಅನ್ನು ಕಳೆಯಿರಿ.", "-y + 11", "-y + 11", ["y + 11", "-y - 11", "2y - 11"], ["y + 11", "-y - 11", "2y - 11"], "Sum = 3x - 2y. Subtracting 3x - y - 11 gives -y + 11.", "ಮೊತ್ತ = 3x - 2y. 3x - y - 11 ನ್ನು ಕಳೆದಾಗ -y + 11 ಸಿಗುತ್ತದೆ.")); i4+=1

qs4.append(make_multi(f"c7_math_alg_{i4:03d}", 2, "Which of the following are like terms?", "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುವು ಸಜಾತೀಯ ಪದಗಳು?", ["3xy, -5yx, 2xy", "4x²y, -x²y"], ["3xy, -5yx, 2xy", "4x²y, -x²y"], ["3x², 3y²", "2xy, 2x"], ["3x², 3y²", "2xy, 2x"], "Like terms have the exact same variables and powers.", "ಸಜಾತೀಯ ಪದಗಳು ನಿಖರವಾಗಿ ಒಂದೇ ಚರಾಕ್ಷರಗಳನ್ನು ಮತ್ತು ಘಾತಗಳನ್ನು ಹೊಂದಿರುತ್ತವೆ.")); i4+=1
qs4.append(make_multi(f"c7_math_alg_{i4:03d}", 2, "Which expressions evaluate to 10 when x=2, y=3?", "x=2, y=3 ಆದಾಗ ಯಾವ ಅಭಿವ್ಯಕ್ತಿಗಳ ಬೆಲೆ 10 ಆಗುತ್ತದೆ?", ["2x + 2y", "5x"], ["2x + 2y", "5x"], ["3x + y", "x² + y²"], ["3x + y", "x² + y²"], "2(2)+2(3) = 10; 5(2) = 10.", "2(2)+2(3) = 10; 5(2) = 10.")); i4+=1
qs4.append(make_multi(f"c7_math_alg_{i4:03d}", 2, "Which of these are binomials?", "ಇವುಗಳಲ್ಲಿ ಯಾವುವು ದ್ವಿಪದೋಕ್ತಿಗಳು?", ["x + 2", "3x² - y"], ["x + 2", "3x² - y"], ["xyz", "x + y + z"], ["xyz", "x + y + z"], "Binomials have exactly two terms separated by + or -.", "ದ್ವಿಪದೋಕ್ತಿಗಳು + ಅಥವಾ - ನಿಂದ ಪ್ರತ್ಯೇಕಿಸಲ್ಪಟ್ಟ ನಿಖರವಾಗಿ ಎರಡು ಪದಗಳನ್ನು ಹೊಂದಿರುತ್ತವೆ.")); i4+=1
qs4.append(make_multi(f"c7_math_alg_{i4:03d}", 3, "Identify the terms with coefficient -2.", "ಸಹಗುಣಕ -2 ಇರುವ ಪದಗಳನ್ನು ಗುರುತಿಸಿ.", ["-2x", "-2xyz"], ["-2x", "-2xyz"], ["2x", "-x²"], ["2x", "-x²"], "The numerical multiplier must be exactly -2.", "ಸಂಖ್ಯಾ ಗುಣಕವು ನಿಖರವಾಗಿ -2 ಆಗಿರಬೇಕು.")); i4+=1

qs4.append(make_match(f"c7_math_alg_{i4:03d}", 1, "Match the algebraic expression with its type.", "ಬೀಜಗಣಿತದ ಅಭಿವ್ಯಕ್ತಿಯನ್ನು ಅದರ ಪ್ರಕಾರದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("3x", "Monomial"), ("x + y", "Binomial"), ("x + y + z", "Trinomial"), ("4x²y", "Monomial")], [("3x", "ಏಕಪದೋಕ್ತಿ"), ("x + y", "ದ್ವಿಪದೋಕ್ತಿ"), ("x + y + z", "ತ್ರಿಪದೋಕ್ತಿ"), ("4x²y", "ಏಕಪದೋಕ್ತಿ")], "Count the number of terms.", "ಪದಗಳ ಸಂಖ್ಯೆಯನ್ನು ಎಣಿಸಿ.")); i4+=1
qs4.append(make_match(f"c7_math_alg_{i4:03d}", 2, "Match the phrase to the algebraic expression.", "ವಾಕ್ಯವನ್ನು ಬೀಜಗಣಿತದ ಅಭಿವ್ಯಕ್ತಿಯೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("Sum of x and y", "x + y"), ("Product of x and y", "xy"), ("x subtracted from y", "y - x"), ("Twice of x", "2x")], [("x ಮತ್ತು y ಗಳ ಮೊತ್ತ", "x + y"), ("x ಮತ್ತು y ಗಳ ಗುಣಲಬ್ಧ", "xy"), ("y ನಿಂದ x ಅನ್ನು ಕಳೆಯುವುದು", "y - x"), ("x ನ ಎರಡರಷ್ಟು", "2x")], "Translate words into algebra.", "ಪದಗಳನ್ನು ಬೀಜಗಣಿತಕ್ಕೆ ಭಾಷಾಂತರಿಸಿ.")); i4+=1
qs4.append(make_match(f"c7_math_alg_{i4:03d}", 2, "Match the expression with its value when x=2.", "x=2 ಆದಾಗ ಅಭಿವ್ಯಕ್ತಿಯನ್ನು ಅದರ ಬೆಲೆಯೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("x + 3", "5"), ("2x - 1", "3"), ("x²", "4"), ("10 / x", "5")], [("x + 3", "5"), ("2x - 1", "3"), ("x²", "4"), ("10 / x", "5")], "Substitute x=2 and calculate.", "x=2 ಎಂದು ಆದೇಶಿಸಿ ಮತ್ತು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ.")); i4+=1
qs4.append(make_match(f"c7_math_alg_{i4:03d}", 3, "Match the expression to its simplified form.", "ಅಭಿವ್ಯಕ್ತಿಯನ್ನು ಅದರ ಸಂಕ್ಷಿಪ್ತ ರೂಪದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("2x + 3x", "5x"), ("5x - 2x + x", "4x"), ("3(x+2)", "3x + 6"), ("2x * 3x", "6x²")], [("2x + 3x", "5x"), ("5x - 2x + x", "4x"), ("3(x+2)", "3x + 6"), ("2x * 3x", "6x²")], "Combine like terms and multiply.", "ಸಜಾತೀಯ ಪದಗಳನ್ನು ಸೇರಿಸಿ ಮತ್ತು ಗುಣಿಸಿ.")); i4+=1
qs4.append(make_match(f"c7_math_alg_{i4:03d}", 3, "Match the term with its numerical coefficient.", "ಪದವನ್ನು ಅದರ ಸಂಖ್ಯಾ ಸಹಗುಣಕದೊಂದಿಗೆ ಹೊಂದಿಸಿ.", [("-5xy", "-5"), ("x", "1"), ("-y", "-1"), ("2/3 xy", "2/3")], [("-5xy", "-5"), ("x", "1"), ("-y", "-1"), ("2/3 xy", "2/3")], "The number factor is the coefficient.", "ಸಂಖ್ಯೆಯ ಅಪವರ್ತನವೇ ಸಹಗುಣಕ.")); i4+=1

# Save all files
with open(os.path.join(OUT_DIR, "rational_numbers.json"), "w", encoding="utf-8") as f:
    json.dump(qs1, f, ensure_ascii=False, indent=2)
with open(os.path.join(OUT_DIR, "practical_geometry.json"), "w", encoding="utf-8") as f:
    json.dump(qs2, f, ensure_ascii=False, indent=2)
with open(os.path.join(OUT_DIR, "perimeter_area.json"), "w", encoding="utf-8") as f:
    json.dump(qs3, f, ensure_ascii=False, indent=2)
with open(os.path.join(OUT_DIR, "algebraic_expressions.json"), "w", encoding="utf-8") as f:
    json.dump(qs4, f, ensure_ascii=False, indent=2)

print(f"Generated files in {OUT_DIR}")
print(f"QS1: {len(qs1)}, QS2: {len(qs2)}, QS3: {len(qs3)}, QS4: {len(qs4)}")
